---
_type: PltConcept
_label: 'Abstractor'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
tags:
  - 'syntax grammar'
---

- Practical foundations for programming languages 's notation

    $x_1,\dots, x_n.a$ -> Within $a$, we can additionally use $x_1,\dots, x_n$.
