---
_type: PltConcept
_label: 'Actual parameter/argument'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/01-chapter-1-learning-smol-standard-model-of-languages.td")
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/02-chapter-2-evaluation.td")
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/01-part-i-judgments-and-rules/01-chapter-1-abstract-syntax.td")
tags:
  - 'language feature design'
  - 'semantics'
  - 'syntax grammar'
---

::: info
(Syntax & Grammar) According to Practical foundations for programming languages , the child of an Operator in an [Abstract syntax tree (AST)](/plt/concepts/abstract-syntax-tree-ast).
:::
