---
_type: Concept
_label: 'Antecedent'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'logic'
---

The part above the line in a typing rule - the ${fref("programming-language-theory/concepts/premise.td")}s that must hold before the ${fref("programming-language-theory/concepts/conclusion.td")} can be drawn (\"if\" part).

The part **above** the line in a typing rule - the Premises that must hold before the Conclusion can be drawn ("if" part).
