---
_type: PltConcept
_label: 'Backward chaining'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
tags:
  - 'logic'
  - 'proof reason technique'
  - 'set theory relation'
---

A proof technique for ${fref("programming-language-theory/concepts/judgment.td")}s that starts from the desired judgement and works backwards towards the ${fref("programming-language-theory/concepts/axiom.td")}s.
