---
_type: PltConcept
_label: 'Behavioral/Observational/Contextual equivalence'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/03-part-i-untyped-systems/03-chapter-5-the-untyped-pure-lambda-calculus.td")
tags:
  - 'program analysis'
  - 'semantics'
---

Example: $\lambda x.\ x \simeq \lambda x.\ (\lambda y.\ y)\ x$
