---
_type: PltConcept
_label: 'Big step natural operational semantics small step'
journey: fref("programming-language-theory/index.td")
status: 'learning'
---

A style of semantic which defines evaluation via ${fref("programming-language-theory/concepts/evaluation-statement-judgement.td")} of the form $t \\Downarrow v$, relating a term directly to its final value in a single derivation rather than through int

A style of semantic which defines evaluation via Evaluation statement/judgement of the form $t \Downarrow v$, relating a term directly to its final value in a single derivation rather than through intermediate steps.
