---
_type: PltConcept
_label: 'Branch coverage'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'design principle'
---

A testing metric requiring that every branch (true/false of each conditional) is executed at least once - difficult to achieve in testing but automatic in type checking since type checkers traverse bo

A testing metric requiring that **every branch** (true/false of each conditional) is executed at least once - difficult to achieve in testing but **automatic** in type checking since type checkers traverse both branches of conditionals.
