---
_type: PltConcept
_label: 'Class extension'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
tags:
  - 'language feature design'
  - 'programming paradigm'
  - 'syntax grammar'
---

(Java) The { ... } part in class Sub extends Sup { ... }, can be conceptually viewed as a ${fref("programming-language-theory/concepts/mixin.td")} specifically applied to Sup.

(Java) The `\{ ... \}` part in `class Sub extends Sup \{ ... \}`, can be conceptually viewed as a Mixin specifically applied to `Sup`.
