---
_type: PltConcept
_label: 'Class'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
tags:
  - 'language feature design'
  - 'programming paradigm'
---

A blueprint or template that defines the structure (fields) and behavior (methods) for creating objects, serving as a factory for instantiating objects with shared characteristics.
