---
_type: PltConcept
_label: 'Closure'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/01-chapter-1-learning-smol-standard-model-of-languages.td")
---

::: info
(Language feature/design, Semantics) A function value that remembers its surrounding ${fref("programming-language-theory/concepts/environment.td")}.
:::
