---
_type: PltConcept
_label: 'Closed term'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/03-part-i-untyped-systems/03-chapter-5-the-untyped-pure-lambda-calculus.td")
tags:
  - 'lambda calculus'
  - 'syntax grammar'
---

A ${fref("programming-language-theory/concepts/lambda-term.td")} with no ${fref("programming-language-theory/concepts/free-variable.td")}.
