---
_type: PltConcept
_label: 'Compiler'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
tags:
  - 'compiler implementation'
---

Mathematically, denote $\\mathcal{P}_S$ as the set of programs in the source language and $\\mathcal{P}_T$ as the set of programs in the target language. Then, a compiler is a function $C: \\mathcal{P}_S \\to \\mathcal{P}_T$

Mathematically, denote $\mathcal{P}_S$ as the set of programs in the source language and $\mathcal{P}_T$ as the set of programs in the target language. Then, a compiler is a function $C: \mathcal{P}_S \to \mathcal{P}_T$.
