---
_type: PltConcept
_label: 'Currying'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
tags:
  - 'language feature design'
---

The act of turning a multi-parameter function into a ${fref("programming-language-theory/concepts/higher-order-function.td")}  that accepts one argument and returns a partially-applied version of the original function.
