---
_type: Concept
_label: 'Decision procedure'
journey: fref("programming-language-theory/index.td")
status: 'learning'
tags:
  - 'computation theory'
  - 'data-structure-algorithm'
  - 'logic'
---

An algorithm that always terminates and correctly answers yes/no for any instance of a given problem class (like propositional satisfiability or type equivalence).

An **algorithm** that always terminates and correctly answers yes/no for any instance of a given problem class (like propositional satisfiability or type equivalence).
