---
_type: Concept
_label: 'Derivable'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
tags:
  - 'linguistics'
  - 'logic'
  - 'set-theory-relation'
  - 'syntax grammar'
---

A property of an ${fref("programming-language-theory/concepts/evaluation-statement-judgement.td")} that it can be derived using the evaluation rules in the calculus.
