---
_type: PltConcept
_label: 'Desired property: value is in normal form'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
tags:
  - 'lambda calculus'
  - 'semantics'
---

A desirable property of a ${fref("programming-language-theory/concepts/lambda-calculus.td")} where every value is in ${fref("programming-language-theory/concepts/normal-form.td")}. This property must hold in all system.
