---
_type: PltConcept
_label: 'Desired property: normal form implies values'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
tags:
  - 'lambda calculus'
  - 'semantics'
---

A desirable property of a ${fref("programming-language-theory/concepts/lambda-calculus.td")} where there's no ${fref("programming-language-theory/concepts/stuck-term.td")}. This property may not hold in most systems.
