---
_type: Concept
_label: 'Desugarer'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-3-syntactic-sugar.td")
---

A ${fref("programming-language-theory/concepts/compiler.td")} phase or program that transforms ${fref("programming-language-theory/concepts/syntactic-sugar.td")} into core language constructs, typically running before interpretation or further compilation stages.
