---
_type: PltConcept
_label: 'Desugar'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-3-syntactic-sugar.td")
tags:
  - 'compiler implementation'
  - 'language feature design'
  - 'metaprogramming self reflection'
  - 'syntax grammar'
---

The process of transforming ${fref("programming-language-theory/concepts/syntactic-sugar.td")} or high-level constructs into more primitive forms in the ${fref("programming-language-theory/concepts/core-calculus-language.td")}, simplifying the interpreter or compiler implementation.
