---
_type: PltConcept
_label: 'Formal parameter'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
tags:
  - 'language feature design'
  - 'syntax grammar'
---

The variable declared in a function definition that receive values when called - placeholders in the function signature.
