---
_type: PltConcept
_label: 'Forward chaining'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

A proof technique for ${fref("programming-language-theory/concepts/judgment-form.td")}s that starts with an ${fref("programming-language-theory/concepts/axiom.td")} and tries to derive the desired judgment.
