---
_type: Concept
_label: 'Function definition'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
tags:
  - 'language-feature-design'
  - 'syntax grammar'
---

A syntactic construct that declares a function by specifying its name (optionally), ${fref("programming-language-theory/concepts/formal-parameter.td")}s, and body - establishing a binding between the name and the corresponding abstraction.
