---
_type: PltConcept
_label: 'Gradual typing'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'language feature design'
  - 'semantics'
  - 'type theory'
---

Fully untyped <---------------> Fully typed

```scheme
Fully untyped <---------------> Fully typed
(Python)           Gradual           (OCaml)
               (TypeScript, Typed Racket)
```
