---
_type: Concept
_label: 'Hypothesis'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
tags:
  - 'language-feature-design'
  - 'logic'
---

::: info
(Formal system, Proof/Reason technique, Language feature/design) [Rocq] A **named assumption** in the proof context that can be used to justify proof steps, introduced by tactics like `intros` or `assert`.
:::
