---
_type: PltConcept
_label: 'Import'
journey: fref("programming-language-theory/index.td")
status: 'learning'
tags:
  - 'language feature design'
  - 'programming paradigm'
  - 'semantics'
  - 'syntax grammar'
---

[Rocq] A **command** in Rocq:(/programming-language-theory/concepts/rocq) that brings names from a loaded [module](/programming-language-theory/concepts/module) into the current namespace, allowing unqualified access (often combined as `Require Import`).
