---
_type: PltConcept
_label: 'Inductive definition'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
tags:
  - 'proof reason technique'
  - 'set theory relation'
---

Tools: Rocq (formerly Coq)

- (Proof/Reason technique, Set theory & Relation) A **definition technique** that specifies a set or type by its base cases and rules for building new elements from existing ones.
- (Proof/Reason technique, Set theory & Relation) A definition technique that specifies a set as the strongest set that is closed under a set of rules to derive membership of its elements.
