---
_type: PltConcept
_label: 'Inductive definition judgment form'
journey: fref("programming-language-theory/index.td")
status: 'learning'
---

A **definition technique** that specifies a set or type by its base cases and rules for building new elements from existing ones.

A definition technique that specifies a set as the strongest set that is closed under a set of rules to derive membership of its elements.
