---
_type: PltConcept
_label: 'Inductive type'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
tags:
  - 'language feature design'
  - 'type theory'
---

Tools: Rocq (formerly Coq)

::: info
(Type theory, Formal system) A **type** defined by a finite set of ${fref("programming-language-theory/concepts/constructor.td")}s that specify all possible ways to build its values, enabling ${fref("programming-language-theory/concepts/pattern-matching.td")} and ${fref("programming-language-theory/concepts/structural-recursion.td")} (like `nat`, `list`, or `tree`).
:::
