---
_type: PltConcept
_label: 'Interpreter'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
tags:
  - 'compiler implementation'
  - 'runtime'
---

Mathematically, denote $\mathcal{P}_L$ as the set of programs written in the language $L$ and $V$ the set of all possible values, an interpreter is a function $I: \mathcal{P}_L \to V$.
