---
_type: PltConcept
_label: 'Introduction rule'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/02-chapter-2-evaluation.td")
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/05-chapter-5-types.td")
tags:
  - 'logic'
---

Example:

$$
\frac{A \quad B}{A \land B} \land I
$$
