---
_type: PltConcept
_label: 'Lambda abstraction'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
tags:
  - 'lambda calculus'
  - 'syntax grammar'
---

A ${fref("programming-language-theory/concepts/lambda-term.td")} of the form $\lambda x.\  t$ - a function that binds variable $x$ over body $t$.
