---
_type: PltConcept
_label: 'Lambda term'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
tags:
  - 'lambda calculus'
  - 'syntax grammar'
---

Any expression in the ${fref("programming-language-theory/concepts/lambda-calculus.td")} grammar: a variable, an ${fref("programming-language-theory/concepts/lambda-abstraction.td")}, or an application.
