---
_type: PltConcept
_label: 'Language safety'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-1-introduction.td")
---

::: info
(Language feature/design, Runtime) According to Types and programming languages, from the view of portability, a language whose behavior can be entirely determined by its programmer's manual, that is, it is not subject to the internals of the specific machine it runs on.
:::

::: info
(Language feature/design, Runtime) According to "Type system" [Luca Cardelli, 1996], a language with no [untrapped runtime error](/programming-language-theory/concepts/untrapped-runtime-error) at runtime.
:::

::: info
(Language feature/design, Runtime) According to Programming languages: Application and Interpretation, a language with [partiality](/programming-language-theory/concepts/partiality) operations and reported safety violations.
:::
