---
_type: PltConcept
_label: 'Lexical analysis'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
tags:
  - 'compiler implementation'
  - 'linguistics'
  - 'syntax grammar'
---

::: info
(Syntax & Grammar, Linguistics) The process of classifying texts into ${fref("programming-language-theory/concepts/syntactic-category.td")}s.
:::

- Removing comments and whitespaces.
- Categorizing tokens.
