---
_type: PltConcept
_label: 'Macro system'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-3-syntactic-sugar.td")
---

A language facility that provides programmable syntax transformations through ${fref("programming-language-theory/concepts/macro.td")}s, enabling users to define new syntactic forms that expand into existing language constructs at compile time.
