---
_type: PltConcept
_label: 'Metalanguage'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

The language used to describe, define, or reason about another language (${fref("programming-language-theory/concepts/object-language.td")}) - e.g., English and mathematical notation when specifying ${fref("programming-language-theory/concepts/lambda-calculus.td")}.
