---
_type: PltConcept
_label: 'Natural deduction style'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

A presentation of ${fref("programming-language-theory/concepts/logical-system.td")}s where ${fref("programming-language-theory/concepts/inference-rule.td")}s are organized into ${fref("programming-language-theory/concepts/introduction-rule.td")} and ${fref("programming-language-theory/concepts/elimination-rule.td")} for each connective, with proofs structured as trees that introduce and discharge assumptions.
