---
_type: Concept
_label: 'Object member'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
tags:
  - 'language-feature-design'
  - 'programming paradigm'
---

A component of an object, either a ${fref("programming-language-theory/concepts/field.td")} (data) or a ${fref("programming-language-theory/concepts/method.td")} (behavior).
