---
_type: Concept
_label: 'Partiality'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'computation theory'
  - 'semantics'
  - 'set-theory-relation'
---

The property of a computation that may not terminate or produce a result for all inputs. ${fref("programming-language-theory/concepts/partial-function.td")}s are undefined for some inputs, unlike ${fref("programming-language-theory/concepts/total-function.td")}s which always return a value.
