---
_type: PltConcept
_label: 'Preorder'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
---

A ${fref("programming-language-theory/concepts/binary-relation.td")} that is ${fref("programming-language-theory/concepts/reflexive.td")} and ${fref("programming-language-theory/concepts/transitive.td")}.
