---
_type: Concept
_label: 'Programming model'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
tags:
  - 'data-structure-algorithm'
  - 'programming paradigm'
---

A conceptual framework defining how computations are structured and executed (like shared memory, ${fref("programming-language-theory/concepts/message-passing.td")}, or ${fref("programming-language-theory/concepts/map-reduce.td")}), abstracting over hardware details.

A **conceptual framework** defining how computations are structured and executed (like shared memory, message passing, or map-reduce), abstracting over hardware details.
