---
_type: PltConcept
_label: 'Proof by rewriting'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

- (Proof/Reason technique, Logic) A ${fref("programming-language-theory/concepts/proof-technique.td")} that transforms expressions by substituting equals for equals, using known equalities to reshape the ${fref("programming-language-theory/concepts/goal.td")}.
- (Formal system, Proof/Reason technique, Language feature/design, Programming paradigm) Rocq A Proof techniques in Rocq (via `rewrite`) that substitutes equals for equals using a known equality to transform the Goal.
