---
_type: Concept
_label: 'Prototype'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
tags:
  - 'language-feature-design'
  - 'programming paradigm'
---

An object that serves as a template for creating other objects through cloning, used in prototype-based languages like JavaScript as an alternative to class-based ${fref("programming-language-theory/concepts/inheritance.td")}, generalizing class-based inheritance.
