---
_type: PltConcept
_label: 'Reflexive'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
tags:
  - 'set theory relation'
---

A property of a ${fref("programming-language-theory/concepts/binary-relation.td")} $R$ on a set $T$ such that $t\ R\ t$ for every $t \in T$.
