---
_type: PltConcept
_label: 'Representation'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

A concrete encoding of abstract data (e.g., the numeral 5 can be represented as \"101\", S(S(S(S(S O)))), or 0x05).

A **concrete encoding** of abstract data (e.g., the numeral `5` can be represented as `"101"`, `S(S(S(S(S O))))`, or `0x05`).
