---
_type: PltConcept
_label: 'Rule'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/03-part-i-untyped-systems/01-chapter-3-untyped-arithmetic-expressions.td")
  - fref("programming-language-theory/books/software-foundations/01-logical-foundations/02-chapter-2-inductive-definitions.td")
tags:
  - 'logic'
---

Short-hand for ${fref("programming-language-theory/concepts/inference-rule.td")}.
