---
_type: PltConcept
_label: 'Runtime error'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/03-part-i-untyped-systems/01-chapter-3-untyped-arithmetic-expressions.td")
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/01-chapter-1-learning-smol-standard-model-of-languages.td")
tags:
  - 'lambda calculus'
  - 'runtime'
  - 'semantics'
---

::: info
(Runtime) An error that happens at runtime.
:::
