---
_type: PltConcept
_label: 'Sequence'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
tags:
  - 'order lattice theory'
  - 'set theory relation'
---

An ordered collection of elements indexed by natural numbers - formally, a function from $\mathbb{N}$ to some set, denoted $(a_0, a_1, a_2, ...)$ or $(a_i)_i\in\mathbb{N}$.
