---
_type: Concept
_label: 'Side-effect'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
tags:
  - 'language-feature-design'
  - 'programming paradigm'
---

An observable interaction with the outside world or modification of state beyond returning a value, such as I/O, mutation, or exceptions.
