---
_type: PltConcept
_label: 'Static dispatch'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
tags:
  - 'language feature design'
  - 'program analysis'
  - 'programming paradigm'
---

Method resolution that occurs at compile time based on some known (may be imprecise) static properties (such as types) of the receiver, as opposed to ${fref("programming-language-theory/concepts/dynamic-dispatch.td")} which resolves at runtime based on the actual dynamic properties.
