---
_type: Concept
_label: 'Static type'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'language-feature-design'
  - 'program analysis'
  - 'type theory'
---

A type that is determined and checked at compile time, before the program runs, as opposed to dynamic types which are checked at runtime.
