---
_type: PltConcept
_label: 'Structural/Abstract syntax'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/03-part-i-untyped-systems/01-chapter-3-untyped-arithmetic-expressions.td")
  - fref("programming-language-theory/books/types-and-programming-languages/03-part-i-untyped-systems/03-chapter-5-the-untyped-pure-lambda-calculus.td")
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/01-part-i-judgments-and-rules/01-chapter-1-abstract-syntax.td")
tags:
  - 'compiler implementation'
  - 'syntax grammar'
---

::: info
(Syntax & Grammar) According to Practical foundations for programming languages, the program's tree structure ([Abstract syntax tree (AST)](/plt/concepts/abstract-syntax-tree-ast)) showing how phrases are built from ${fref("programming-language-theory/concepts/operator.td")}s and subphrases.
:::
