---
_type: PltConcept
_label: 'Structural abstract syntax concrete surface syntax'
journey: fref("programming-language-theory/index.td")
status: 'learning'
---

::: info
(Syntax & Grammar) According to Practical foundations for programming languages, the program's tree structure ([Abstract syntax tree (AST)](/plt/concepts/abstract-syntax-tree-ast)) showing how phrases are built from ${fref("programming-language-theory/concepts/operator.td")}s and subphrases.
:::
