---
_type: PltConcept
_label: 'Structural type'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'language feature design'
  - 'semantics'
  - 'type theory'
---

A type defined by its shape (fields, methods, signatures) rather than its name - two types are equal if they have the same structure.

A type defined by its **shape** (fields, methods, signatures) rather than its name - two types are equal if they have the same structure.
