---
_type: PltConcept
_label: 'Structural induction'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

A proof technique for inductively defined structures, where a property is shown for all elements by proving base cases and proving composite cases assuming the property holds for all immediate sub-structures.
