---
_type: PltConcept
_label: 'Subclass'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/05-chapter-5-types.td")
tags:
  - 'language feature design'
  - 'programming paradigm'
  - 'semantics'
---

::: info
(Semantics, Language feature/design, Programming paradigm) A ${fref("programming-language-theory/concepts/class.td")} that extends a parent class.
:::
