---
_type: PltConcept
_label: 'Subtype'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'language feature design'
  - 'programming paradigm'
  - 'semantics'
  - 'set theory relation'
  - 'type theory'
---

A type $X$ that can be used wherever type $Y$ is expected - $X$ is \"more specific\" than $Y$.

A type $X$ that can be **used wherever** type $Y$ is expected - $X$ is "more specific" than $Y$.
