---
_type: PltConcept
_label: 'Symbol'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
tags:
  - 'syntax grammar'
---

As per Practical foundations for programming languages's terminology, an index to the families of operators. Given an ${fref("programming-language-theory/concepts/indexed-operator.td")} $o$ and a symbol $u$, $o[u]$ is an operator.
