---
_type: PltConcept
_label: 'Syntactic sugar'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-3-syntactic-sugar.td")
---

A more convenient or readable syntax that is transformed into a ${fref("programming-language-theory/concepts/core-calculus-language.td")} construct, providing expressiveness without extending the language's fundamental semantics.
