---
_type: Concept
_label: 'Syntactic abstraction'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-3-syntactic-sugar.td")
tags:
  - 'language-feature-design'
  - 'metaprogramming-self-reflection'
  - 'programming paradigm'
  - 'syntax grammar'
---

A mechanism for defining new syntax forms, typically through ${fref("programming-language-theory/concepts/macro.td")}s, that expand into existing language constructs. Enables language extension without modifying the core implementation.
