---
_type: PltConcept
_label: 'Tactic modifier'
journey: fref("programming-language-theory/index.td")
status: 'learning'
tags:
  - 'syntax grammar'
---

Tools: Rocq (formerly Coq)

- (Syntax & Grammar, Language feature/design) A **syntactic addition** to a ${fref("programming-language-theory/concepts/tactic.td")} that alters its behavior, such as intro patterns for `intros` or occurrence selectors for `rewrite`.
