---
_type: PltConcept
_label: 'Transitive'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
tags:
  - 'set theory relation'
---

A property of a ${fref("programming-language-theory/concepts/binary-relation.td")} $R$ on a set $T$ such that if $t_0\ R\ t_1$ and $t_1\ R\ t_2$ then $t_0\ R\ t_2$, for every $t_0$, $t_1$, $t_2$ $\in T$.
