---
_type: Concept
_label: 'Truthy'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
tags:
  - 'language-feature-design'
  - 'semantics'
---

A value that evaluates as true in a boolean context despite not being literally true (like non-zero numbers or non-empty strings in dynamic languages).

A **value** that evaluates as true in a boolean context despite not being literally `true` (like non-zero numbers or non-empty strings in dynamic languages).
