---
_type: Concept
_label: 'Type variable'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'language-feature-design'
  - 'syntax grammar'
  - 'type theory'
---

A placeholder (e.g., $T$, $U$, $\\alpha$) representing an unknown or generic type - gets instantiated to a concrete type during type checking or remains polymorphic.

A **placeholder** (e.g., $T$, $U$, $\alpha$) representing an unknown or generic type - gets instantiated to a concrete type during type checking or remains polymorphic.
