---
_type: Concept
_label: 'Type environment'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'semantics'
  - 'type theory'
---

A mapping from variable names to their types, often written as $\Gamma$, that tracks type bindings in scope during ${fref("programming-language-theory/concepts/type-checker.td")} analysis, extended when entering new binding forms.
