---
_type: PltConcept
_label: 'Type compatibility'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'language feature design'
  - 'semantics'
  - 'set theory relation'
  - 'type theory'
---

A relation between types that implies ${fref("programming-language-theory/concepts/substitutability.td")}. A static approximation of Substitutability.
