---
_type: Concept
_label: 'Union type retrofitted type system'
journey: fref("programming-language-theory/index.td")
status: 'learning'
---

**Union type:** An **untagged**, **ad-hoc** combination of existing independent types (e.g., `(U mt node)`) - unlike ${fref("programming-language-theory/concepts/sum-type.td")} (${fref("programming-language-theory/concepts/algebraic-data-type.td")}) where ${fref("programming-language-theory/concepts/type-variant.td")} are **tagged** and **defined together** as part of one type.
