---
_type: PltConcept
_label: 'Union type'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'language feature design'
  - 'type theory'
---

Union type: An untagged, ad-hoc combination of existing independent types (e.g., (U mt node)) - unlike ${fref("programming-language-theory/concepts/sum-type.td")} (${fref("programming-language-theory/concepts/algebraic-data-type.td")}) where ${fref("programming-language-theory/concepts/type-variant.td")} are tagged and defined together as part of one

**Union type:** An **untagged**, **ad-hoc** combination of existing independent types (e.g., `(U mt node)`) - unlike Sum type (Algebraic data types) where Type variant are **tagged** and **defined together** as part of one type.
