---
_type: PltConcept
_label: 'Valence'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
tags:
  - 'syntax grammar'
---

The specification of how many variables a subterm binds and what ${fref("programming-language-theory/concepts/sort.td")}s (types) those variables have.
