---
_type: PltConcept
_label: 'Value environment'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'runtime'
  - 'semantics'
---

A mapping from variable names to runtime values used during interpretation.

A mapping from variable names to **runtime values** used during interpretation.
