---
_type: PltConcept
_label: 'Variable definition'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
tags:
  - 'language feature design'
  - 'syntax grammar'
---

A syntactic construct that introduces a new variable name and establishes a binding - optionally with an initial value (e.g., let x = 5).

A syntactic construct that introduces a new variable name and establishes a binding - optionally with an initial value (e.g., `let x = 5`).
