allowBuilds:
  '@typerighter/rpc-server': true
minimumReleaseAgeExclude:
  - '@typerighter/rpc-client@0.23.0 || 0.24.0 || 0.24.1'
  - '@typerighter/rpc-server@0.23.0 || 0.24.0 || 0.24.1'
  - typerighter@0.23.0 || 0.24.0 || 0.24.1
