allowBuilds:
  '@typerighter/rpc-server': true
minimumReleaseAgeExclude:
  - '@typerighter/rpc-client@0.17.1 || 0.17.3'
  - '@typerighter/rpc-server@0.17.1 || 0.17.3'
  - typerighter@0.17.1 || 0.17.3
