---
_type: Concept
title: 'Figma'
journey: fref("journeys/design/index.td")
status: 'reviewing'
tags:
  - 'design-tool'
---

A browser-based, collaborative vector design tool used for creating ${fref("journeys/design/concepts/user-interface-ui.td", "user interfaces")}, ${fref("journeys/design/concepts/prototyping.td", "prototypes")}, and managing ${fref("journeys/design/concepts/design-system.td", "design systems")} in real-time.
