---
_type: Flashcard
question: "According to robert (bob) harper, what is a sort, syntactically?"
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/sort.td")
books:
  - fref("journeys/programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
---

::: flashcard
${question}
=== key
Basically a syntactic category of an AST.
:::
