---
_type: Flashcard
deck: 'pure-lambda-calculus'
concepts:
  - fref("journeys/programming-language-theory/concepts/value.td")
  - fref("journeys/programming-language-theory/concepts/normal-form.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
Are normal forms always a value?
=== key
Normal forms can be stuck terms.
:::
