---
_type: Flashcard
deck: 'programming-language-basic'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
---

::: flashcard
Are languages inherently compiled/interpreted?
=== key
- **No**: Languages are not inherently compiled or interpreted.
- Language specifications only specify syntax and semantics, but usually do not require a specific implementation.
- Examples:
  - C++ can be interpreted.
  - Python can be compiled.
  - Javascript runtimes like browser opt for a hybrid approach.
:::
