---
_type: Flashcard
question: "Are values always in normal form?"
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/normal-form.td")
  - fref("journeys/programming-language-theory/concepts/value.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
${question}
=== key
May not be, but should hold for all meaningful calculus.
:::
