---
_type: Flashcard
question: "Are there booleans, strings, numbers defined in rocq?"
deck: 'rocq-programming-language'
concepts:
  - fref("journeys/programming-language-theory/concepts/rocq.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
${question}
=== key
Everything can be defined from scratch and there are no built-in boolean, string or number. However, the standard library still includes those.
:::
