---
_type: Flashcard
question: "Can a language implementer choose whether to compile or interpret a given language?"
deck: 'compiler-implementation'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
---

::: flashcard
${question}
=== key
Yes. A language specification doesn't enforce compilation or interpretation.
:::
