---
_type: Flashcard
question: "Does a REPL enforce a kind of implementation (compilation/interpretation)?"
deck: 'compiler-implementation'
concepts:
  - fref("journeys/programming-language-theory/concepts/read-eval-print-loop-repl.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
---

::: flashcard
${question}
=== key
No. But mostly a REPL implements interpretation.
:::
