---
_type: Flashcard
question: "Does a language specify how it should be evaluated?"
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/compiler.td")
  - fref("journeys/programming-language-theory/concepts/interpreter.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
---

::: flashcard
${question}
=== key
No.
:::
