---
_type: Flashcard
deck: 'pure-lambda-calculus'
concepts:
  - fref("journeys/programming-language-theory/concepts/application-function-call.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
Formalize function application and describe its notation in pure lambda calculus?
=== key
Function application is called a Beta-redex/Reducible expression in pure lambda calculus.

Notation: $t_1\ t_2$ in which $t_1$  is a lambda abstraction.
:::
