---
_type: Flashcard
question: "How to use inductive definition to define functions?"
deck: 'logic-tools'
concepts:
  - fref("journeys/programming-language-theory/concepts/inductive-definition.td")
  - fref("journeys/programming-language-theory/concepts/function.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
${question}
=== key
- Define a relation between inputs and outputs of the function using Inductive definition.
- Then prove that for each set of inputs, the output is unique.
:::
