---
_type: Flashcard
question: 'How does the "flow typing" concept relate to the "parse, do not validate" principle and "boolean blindness"?'
deck: 'general'
concepts:
  - fref("journeys/programming-language-theory/concepts/flow-typing.td")
  - fref("journeys/programming-language-theory/concepts/flow-sensitive-typing.td")
  - fref("journeys/programming-language-theory/concepts/boolean-blindness.td")
---

::: flashcard
${question}
=== key
️ Interpreters & projects : dboxide
:::
