---
_type: Flashcard
deck: 'set-theory-relation'
concepts:
  - fref("journeys/programming-language-theory/concepts/term.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
How can the inductive definition define terms as trees?
=== key
The inductive definition starts with a base term and builds a composite term from smaller terms. -> A term's structure is hierarchical.
:::
