---
_type: Flashcard
deck: 'rocq-programming-language'
concepts:
  - fref("journeys/programming-language-theory/concepts/rocq.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
How to invoke a function in rocq?
=== key
Subexpression: `(fn arg1 arg2 ...)`

Top-level: `Compute (fn arg1 arg2 ...).`

Expectation: `Example test: (fn arg1 arg2) = res.`
:::
