---
_type: Flashcard
question: "In an ABT, what is the valence of an argument?"
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/valence.td")
books:
  - fref("journeys/programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
---

::: flashcard
${question}
=== key
The specification of an argument of an operator, specifying the number and the sorts of its bound variables and the sort of itself.
:::
