---
_type: Flashcard
question: "In which ways the lambda calculus can be viewed?"
deck: 'pure-lambda-calculus'
concepts:
  - fref("journeys/programming-language-theory/concepts/lambda-calculus.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
${question}
=== key
- A **simple programming language** in which computations can be described.
- A **mathematical object** about which rigorous statements can be proved.
:::
