---
_type: Flashcard
question: 'Name some classical heavyweight formal methods'
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/hoare-logic.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-1-introduction.td")
---

::: flashcard
${question}
=== key
- Hoare logic.
- Modal logic.
- Algebraic definition language.
- Denotational semantics.
:::
