---
_type: Flashcard
deck: 'programming-language-basic'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation.td")
---

::: flashcard
Should we think in features or paradigms regarding programming languages?
=== key
Modern programming languages are all multi-paradigms and rather mixes of multiple features. It's outdated to think in terms of paradigms.
:::
