---
_type: Flashcard
question: 'The definition of runtime type error'
deck: 'type-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/runtime-type-error.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-1-introduction.td")
---

::: flashcard
${question}
=== key
Runtime type error is the class of program behaviors that a specific type system is designed to eliminate.
:::
