---
_type: Flashcard
question: "The relation between the set of values and the set of terms?"
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/term.td")
  - fref("journeys/programming-language-theory/concepts/value.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
${question}
=== key
The set of values is a subset of the set of terms.
:::
