---
_type: Flashcard
question: "What is a macro?"
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/macro.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-3-syntactic-sugar.td")
---

::: flashcard
${question}
=== key
Macro is a syntactic pattern that gets expanded into other code at compile time.
:::
