---
_type: Flashcard
question: "What is beta reduction?"
deck: 'pure-lambda-calculus'
concepts:
  - fref("journeys/programming-language-theory/concepts/beta-redex-reducible-expression.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
${question}
=== key
The act of reducing a Beta-redex/Reducible expression by substituting the redex's argument into its function body.
:::
