---
_type: Flashcard
deck: 'pure-lambda-calculus'
concepts:
  - fref("journeys/programming-language-theory/concepts/beta-redex-reducible-expression.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
What is a redex or reducible expression in church's terminology?
=== key
A redex is a term of the form $t_1\ t_2$ such that $t_1$ is a lambda abstraction.
:::
