---
_type: Flashcard
question: "What is a closure in programming language?"
deck: 'programming-language-basic'
concepts:
  - fref("journeys/programming-language-theory/concepts/closure.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

::: flashcard
${question}
=== key
A closure is a function that memorizes its surrounding environment, so i can access variables from the outside.
:::
