---
_type: Flashcard
question: "What are the ideas of forward chaining and backward chaining?"
deck: 'proof-technique'
concepts:
  - fref("journeys/programming-language-theory/concepts/forward-chaining.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
${question}
=== key
Forward chaining

Backward chaining
:::
