---
_type: Flashcard
deck: 'other-mathematics'
concepts:
  - fref("journeys/programming-language-theory/concepts/meta-mathematics.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
What is meta-mathematics?
=== key
A branch of meta-mathematics that studies about the properties of mathematical systems.
:::
