---
_type: Flashcard
question: "What are the key considerations in designing conditionals?"
deck: 'compiler-implementation'
concepts:
  - fref("journeys/programming-language-theory/concepts/conditional-expression.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
---

::: flashcard
${question}
=== key
- Which data types are allowed in conditionals?

    Which values are truthy and falsy?

- How to handle diverging datatypes of `then` and `else` expressions.
:::
