---
_type: Flashcard
question: "What are lambda terms and lambda abstractions?"
deck: 'pure-lambda-calculus'
concepts:
  - fref("journeys/programming-language-theory/concepts/lambda-calculus.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
${question}
=== key
Lambda terms are any syntactic constructs in Lambda calculus.

Lambda abstractions are lambda terms of the form $\lambda x.\ \text{term}$.
:::
