---
_type: Flashcard
question: 'What does it mean by the judgment $\gamma \vdash_\mathcal{r} k$, where $\gamma$ is a finite set of basic judgments, $k$ is a basic judgment and $\mathcal{r}$ is a set of rules?'
deck: 'general'
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-3-hypothetical-and-general-judgments.td")
---

::: flashcard
${question}
=== key
:::
