---
_type: Flashcard
question: "What are nominal typing and structural typing?"
deck: 'type-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/nominal-typing.td")
  - fref("journeys/programming-language-theory/concepts/structural-typing.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
---

::: flashcard
${question}
=== key
Nominal typing is a policy that determines type compatibility based on user-provided declarations.

Structural typing is a policy that determines type compatibility based on their structures.
:::
