---
_type: Flashcard
question: "What are some challenges of retrofitting type systems?"
deck: 'compiler-implementation'
concepts:
  - fref("journeys/programming-language-theory/concepts/retrofitted-type-system.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
---

::: flashcard
${question}
=== key
Languages that are previously untyped:

- Encourage patterns that are type-unsound/hard-to-precisely-typed.
- Untypable patterns: `eval`.
- How to coexist with untyped code.
:::
