---
_type: Flashcard
deck: 'logic-tools'
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
What's the difference between a judgment and a judgment form?
=== key
A Judgment is announcement that there is a proof for something.

A Judgment form is a **relation** that defines the syntax and arguments required to make a specific kind of judgment (e.g., the "is a type" relation).
:::
