---
_type: Flashcard
question: "What are the differences between abstract and concrete syntax?"
deck: 'programming-language-basic'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
${question}
=== key
- Concrete/Surface syntax: The language that the programmers actually programs in - usually a sequence of characters.
- Structural/Abstract syntax: The more structured language, easier to reason about & worked on by compiler implementations. Often represented by [Abstract syntax tree (AST)](/journeys/plt/concepts/abstract-syntax-tree-ast).
:::
