---
_type: Flashcard
question: "What are substitution target and subject?"
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/substitution-subject.td")
  - fref("journeys/programming-language-theory/concepts/substitution-target.td")
books:
  - fref("journeys/programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
---

::: flashcard
${question}
=== key
Substitution target: The target term into which variables are substituted.

Substitution subject: The variable that is substituted.
:::
