---
_type: Flashcard
question: "What is a tactic in rocq?"
deck: 'rocq-programming-language'
concepts:
  - fref("journeys/programming-language-theory/concepts/tactic.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
${question}
=== key
A proof command in Rocq, that transforms a goal's state to form a step of a proof.
:::
