---
_type: Flashcard
deck: 'programming-language-basic'
concepts:
  - fref("journeys/programming-language-theory/concepts/binding.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

::: flashcard
What is a binding?
=== key
A binding is a mapping from a variable to a value.
:::
