---
_type: Flashcard
question: "What are the differences between terms and expressions?"
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/term.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
${question}
=== key
Expression is used to denote any syntactic constructs.

Term is used to denote syntactic constructs that represents computation.
:::
