---
_type: Flashcard
question: "What are the approaches to implementing macros?"
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/macro.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-3-syntactic-sugar.td")
---

::: flashcard
${question}
=== key
AST rewriting

Parenthetical language
:::
