---
_type: Flashcard
question: "What is the syntax for imports in rocq?"
deck: 'rocq-programming-language'
concepts:
  - fref("journeys/programming-language-theory/concepts/import.td")
  - fref("journeys/programming-language-theory/concepts/require.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
${question}
=== key
`From Library Require [Import] Module.`
:::
