---
_type: Flashcard
question: "What is a countable set?"
deck: 'set-theory-relation'
concepts:
  - fref("journeys/programming-language-theory/concepts/countable-set.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
---

::: flashcard
${question}
=== key
A set that is finite, or is infinite and a bijection from it into $\mathbb{N}$ exists.
:::
