---
_type: Flashcard
question: "What's the idea of denotational semantics?"
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/denotational-semantics.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
${question}
=== key
A style of semantics that compositionally defines the meaning of each term by mapping it into a mathematical object.
:::
