---
_type: Flashcard
question: "What are the pros and cons of forward chaining search?"
deck: 'proof-technique'
concepts:
  - fref("journeys/programming-language-theory/concepts/forward-chaining.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
${question}
=== key
Quite similar to What are the pros and cons of backward chaining search?, except that forward chaining search is undirected
:::
