---
_type: Flashcard
question: "What is an environment in programming language?"
deck: 'programming-language-basic'
concepts:
  - fref("journeys/programming-language-theory/concepts/environment.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

::: flashcard
${question}
=== key
An environment can be a theoretic construct to store bindings of variables to values/types as part of semantic/type-theoretic reasoning.

An environment can be a runtime data structure that store bindings of variables currently in scope to their values.
:::
