---
_type: Flashcard
question: "What is the operational semantics of boolean expressions?"
deck: 'pure-lambda-calculus'
concepts:
  - fref("journeys/programming-language-theory/concepts/untyped-calculus-of-booleans-and-numbers.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
${question}
=== key
What is the operational semantics of arithmetic expressions?
:::
