---
_type: Flashcard
question: "What are closed terms, free variables, bound variables, binders in lambda calculus?"
deck: 'pure-lambda-calculus'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
${question}
=== key
- Closed term: A term with no free variables.
- Free variable: A variable that is not bound.
- Bound variable: A variable bound by a binder.
- Binder: The $x$ in $\lambda x$.
:::
