---
_type: Flashcard
question: "What is a local binding form?"
deck: 'programming-language-basic'
concepts:
  - fref("journeys/programming-language-theory/concepts/local-binding-form.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

::: flashcard
${question}
=== key
A syntactic construct that introduces a variable with limited scope.
:::
