---
_type: Flashcard
question: "What is a metalanguage?"
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/metalanguage.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
${question}
=== key
The language used to describe, define, or reason about another language.
:::
