---
_type: Flashcard
deck: 'set-theory-relation'
concepts:
  - fref("journeys/programming-language-theory/concepts/transitive-closure.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
---

::: flashcard
What's the standard notation for transitive closure?
=== key
If $R$ is a relation on some set, then $R^+$ is the transitive closure.
:::
