---
_type: Flashcard
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/value.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
What is a value in programming language calculus?
=== key
A syntactic term that is not related by another term in the operational semantics.
:::
