---
_type: Flashcard
question: "What is a normal form?"
deck: 'pure-lambda-calculus'
concepts:
  - fref("journeys/programming-language-theory/concepts/normal-form.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
${question}
=== key
A normal form is a lambda term that does not relate to any other terms by the One-step evaluation relation.
:::
