---
_type: Flashcard
question: "What is a metatheory?"
deck: 'other-mathematics'
concepts:
  - fref("journeys/programming-language-theory/concepts/metatheory.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
${question}
=== key
The study about properties of a formal system, using external reasonings.
:::
