---
_type: Flashcard
question: "What is the portability perspective on language safety?"
deck: 'type-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/language-safety.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-1-introduction.td")
---

::: flashcard
${question}
=== key
A safe language can be totally defined by its programmer's manual.
:::
