---
_type: Flashcard
deck: 'programming-language-basic'
concepts:
  - fref("journeys/programming-language-theory/concepts/primordial-block.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

::: flashcard
What is a primordial block in programming language?
=== key
A block that encompasses the global scope, containing all the builtins.
:::
