---
_type: Flashcard
question: "What are some examples of automated theorem provers?"
deck: 'compiler-implementation'
concepts:
  - fref("journeys/programming-language-theory/concepts/automated-theorem-prover.td")
  - fref("journeys/programming-language-theory/concepts/sat-solver.td")
  - fref("journeys/programming-language-theory/concepts/smt-solver.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/logical-foundations.td")
---

::: flashcard
${question}
=== key
- SAT solver
- SMT solver
- Model checker
:::
