---
_type: Flashcard
question: "What is the difference between formal and actual parameters?"
deck: 'programming-language-basic'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

::: flashcard
${question}
=== key
- Formal parameter: The function parameters as defined in the function headers.
- Actual parameter: The function arguments.
:::
