---
_type: Flashcard
deck: 'programming-language-basic'
concepts:
  - fref("journeys/programming-language-theory/concepts/parallel-simultaneous-let.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

::: flashcard
What is parallel/simultaneous let?
=== key
A parallel/simultaneous let is a syntactic construct in Scheme in which any bindings in the let definition are not visible within the let definition itself.
:::
