---
_type: Flashcard
deck: 'programming-language-basic'
concepts:
  - fref("journeys/programming-language-theory/concepts/first-order-variable.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

::: flashcard
What is a first order variable?
=== key
A variable that ranges over data values (e.g., integers, booleans, records).
:::
