---
_type: Flashcard
question: "What is an example for the tradeoffs between the type system's expressiveness & decidability?"
deck: 'language-theory'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
---

::: flashcard
${question}
=== key
Refined type: Allow the programmers to encode non-zeroness into the the type.

-> Typechecking becomes undecidable.
:::
