---
_type: Flashcard
question: "What is the technique of induction on derivations?"
deck: 'pure-lambda-calculus'
concepts:
  - fref("journeys/programming-language-theory/concepts/induction-on-derivations.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
${question}
=== key
An induction technique in which to prove a specific property about a derivation, we take the induction hypothesis is that every smaller derivations satisfy that property.
:::
