---
_type: Flashcard
question: "What is an instance of an inference rule?"
deck: 'logic-tools'
concepts:
  - fref("journeys/programming-language-theory/concepts/instance-of-an-inference-rule.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
${question}
=== key
An inference rule whose metavariables are replaced with real values.
:::
