---
_type: Flashcard
deck: 'logic-tools'
concepts:
  - fref("journeys/programming-language-theory/concepts/computation-rule.td")
  - fref("journeys/programming-language-theory/concepts/congruence-rule.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
What are computation and congruence rules?
=== key
A computation rule directly reduces the current term.

A congruence rule delegate evaluation to another rule.
:::
