---
_type: Flashcard
question: "What is a rule scheme?"
deck: 'logic-tools'
concepts:
  - fref("journeys/programming-language-theory/concepts/inference-rule.td")
  - fref("journeys/programming-language-theory/concepts/metavariable.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
${question}
=== key
Synonymous with Rule schema - An Inference rule that is parameterized with Metavariables.
:::
