---
_type: Flashcard
question: "What's the strength of axiomatic semantics?"
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/axiomatic-semantics.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
${question}
=== key
The proof rules/laws are of the fore-front focus.
:::
