---
_type: Flashcard
question: 'What does it mean by "everything is a function" in lambda calculus?'
deck: 'pure-lambda-calculus'
concepts:
  - fref("journeys/programming-language-theory/concepts/lambda-calculus.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
${question}
=== key
Every closed terms in Lambda calculus are functions.
:::
