---
_type: Flashcard
question: "What is an object language?"
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/object-language.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
${question}
=== key
The formal language being defined by the metalanguage.
:::
