---
_type: Flashcard
question: "What is an evaluator?"
deck: 'programming-language-basic'
concepts:
  - fref("journeys/programming-language-theory/concepts/evaluator.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
---

::: flashcard
${question}
=== key
An evaluator is a program that reduces a program into a value.
:::
