---
_type: Flashcard
question: "What is the idea of traits?"
deck: 'type-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/trait.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
---

::: flashcard
${question}
=== key
Trait is a generalization of mixin, in that, multiple traits can be applied simultaneously to a class, instead of applying one-at-a-time like mixin. This allows for well-defined and automatic conflict-resolution.
:::
