---
_type: Flashcard
question: "What is automatic memory management?"
deck: 'programming-language-basic'
concepts:
  - fref("journeys/programming-language-theory/concepts/automatic-memory-management.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

::: flashcard
${question}
=== key
Automatic memory management is a set of compile-time or dynamic techniques that allows the dynamic allocation and deallocation of memory without explicit instructions from the programmer.
:::
