---
_type: Flashcard
question: "What is BNF?"
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/bnf.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
${question}
=== key
A specific meta-language that is widely used to describe context-free languages.
:::
