---
_type: Flashcard
question: "What is an REPL?"
deck: 'compiler-implementation'
concepts:
  - fref("journeys/programming-language-theory/concepts/read-eval-print-loop-repl.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
---

::: flashcard
${question}
=== key
A program that provides an interactive interface for programmers to interact with a programming language in an adhoc and highly-responsive fashion. The name represents the typical phases of this interaction: The program reads the input from the user, evaluates it, prints out the result and loops.
:::
