---
_type: Flashcard
question: "What is garbage collection?"
deck: 'programming-language-basic'
concepts:
  - fref("journeys/programming-language-theory/concepts/garbage-collection.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

::: flashcard
${question}
=== key
Garbage collection is a runtime mechanism that utilizes a heuristic to detect and release no-longer-used memory.
:::
