---
_type: Flashcard
question: "What is meta-mathematics?"
deck: 'other-mathematics'
concepts:
  - fref("journeys/programming-language-theory/concepts/meta-mathematics.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
${question}
=== key
A branch of meta-mathematics that studies about the properties of mathematical systems.
:::
