---
_type: Flashcard
question: 'What else can a type system catch other than low-level faults such as invoking non-existent methods'
deck: 'type-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/type-system.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-1-introduction.td")
---

::: flashcard
${question}
=== key
- Access control.
- Arbitrary constraints.
:::
