---
_type: Flashcard
deck: 'rocq-programming-language'
concepts:
  - fref("journeys/programming-language-theory/concepts/constructor-expression.td")
  - fref("journeys/programming-language-theory/concepts/constructor.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
What are constructor expressions in rocq?
=== key
A constructor expression is an expression constructed using a Constructor, effectively creating a member of a set represented by a type.
:::
