---
_type: Flashcard
question: "What is recursive let?"
deck: 'programming-language-basic'
concepts:
  - fref("journeys/programming-language-theory/concepts/recursive-let.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

::: flashcard
${question}
=== key
Recursive let is a syntactic construct in Scheme in which each binding in the let definition is visible anywhere within the let expression.
:::
