---
_type: Flashcard
question: "What is the divergent combinator?"
deck: 'pure-lambda-calculus'
concepts:
  - fref("journeys/programming-language-theory/concepts/divergent-big-omega-combinator.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
${question}
=== key
The Divergent/Big omega combinator:

$$
\Omega = (\lambda x.\ x\ x)\ (\lambda x.\ x\ x)
$$
:::
