---
_type: Flashcard
question: "What is the meaning of a term?"
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/term.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
${question}
=== key
The meaning of a term can be taken to be the final state of the abstract machine running it.
:::
