---
_type: Flashcard
question: "What is a congruence?"
deck: 'set-theory-relation'
concepts:
  - fref("journeys/programming-language-theory/concepts/congruence.td")
books:
  - fref("journeys/programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
---

::: flashcard
${question}
=== key
An equivalence relation that is preserved under a specific operation.
:::
