---
_type: Flashcard
deck: 'rocq-programming-language'
concepts:
  - fref("journeys/programming-language-theory/concepts/rocq.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/logical-foundations.td")
---

::: flashcard
What are the use cases of rocq?
=== key
- As a platform to model programming languages.
- As a tool to write formally certified software and hardware.
- As a functional programming language with dependent types.
- As a proof assistant for higher-order logic.
:::
