---
_type: Flashcard
question: 'What are the cons of lightweight formal methods'
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/type-system.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-1-introduction.td")
---

::: flashcard
${question}
=== key
Not as strong or general as more heavy-weight methods.
:::
