---
_type: Flashcard
question: "What are judgment/assertion, judgment form, judgment instance, judgment form instance's subject? in what notations are they written in?"
deck: 'logic-tools'
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
${question}
=== key
- A judgment form is a relation, interpreted as a Predicate.

    Typically written as $- \ J$ (for unary relation).

- Take the judgment form above, the notation $a\ J$, for some value $a$, is an instance of the judgment form.
- Take the judgment form instance above, $a$ is the judgment form instance's subject.
- A judgment/assertion is a stance on whether an instance of the judgment holds or not.
:::
