---
_type: Flashcard
question: "What are the pros and cons of proof assistants?"
deck: 'logic-tools'
concepts:
  - fref("journeys/programming-language-theory/concepts/proof-assistant-prover.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/logical-foundations.td")
---

::: flashcard
${question}
=== key
- Automated for routine tasks of building proofs.
- Require human guidance for more difficult aspects.
- In general more flexible than Automated theorem prover.
:::
