---
_type: Flashcard
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/denotational-semantics.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
What are the major advantages of denotational semantics?
=== key
Denotational semantics allows the reuse of knowledge drawn from a well-studied domain into programming language design.
:::
