---
_type: Flashcard
question: "What is the relation between objects and closures?"
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/object.td")
  - fref("journeys/programming-language-theory/concepts/closure.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
---

::: flashcard
${question}
=== key
An Object is a Closure with multiple entrypoints.
:::
