---
_type: Flashcard
question: "What is the wildcard pattern in rocq?"
deck: 'rocq-programming-language'
concepts:
  - fref("journeys/programming-language-theory/concepts/rocq.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
${question}
=== key
The wildcard pattern `_` allows matching all values without introducing unnecessary variables.
:::
