---
_type: Flashcard
question: 'What is the relation between "meaning" and "representation"?'
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/representation.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
${question}
=== key
- One representation can have multiple meanings, depending on its usage.
- One meaning can have multiple representation.
:::
