---
_type: Flashcard
question: 'What does "variables in an AST range over some specified sorts" mean?'
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/variable.td")
books:
  - fref("journeys/programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
---

::: flashcard
${question}
=== key
Variables are placeholders for ASTs of some specified sorts.
:::
