---
_type: Flashcard
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/expression-problem.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
---

::: flashcard
What is the expression problem?
=== key
A fundamental tension in language design - how to extend a data abstraction with both **new variants** (data) and **new operations** (functions) without modifying existing code.
:::
