---
_type: Flashcard
question: "What does an inductive definition in rocq do?"
deck: 'rocq-programming-language'
concepts:
  - fref("journeys/programming-language-theory/concepts/rocq.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
${question}
=== key
It allows defining Algebraic data types in Rocq, including Recursive types.

Its name bears resemblance to Inductive definition.
:::
