---
_type: Flashcard
question: "What are there in the rocq system besides the kernel?"
deck: 'rocq-programming-language'
concepts:
  - fref("journeys/programming-language-theory/concepts/rocq.td")
  - fref("journeys/programming-language-theory/concepts/tactic.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/logical-foundations.td")
---

::: flashcard
${question}
=== key
- A large library of common definitions and axioms.
- Powerful tactics for constructing complex proofs semi-automatically.
- A special-purpose programming language for defining new proof-automation tactics for specific situations.
:::
