---
_type: Flashcard
question: "What is an axiom (inference rule)?"
deck: 'logic-tools'
concepts:
  - fref("journeys/programming-language-theory/concepts/inference-rule.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
${question}
=== key
An axiom is an inference rule with no premise.
:::
