---
_type: Flashcard
question: "What is the relation between basic objects and lambdas?"
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/object.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
---

::: flashcard
${question}
=== key
Object is a lambda expression with multiple entrypoints.
:::
