---
_type: Flashcard
question: "What is a metavariable?"
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/metavariable.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
${question}
=== key
A variable of the metalanguage that ranges over terms of a syntactic category.
:::
