---
_type: Flashcard
question: "What is a macro system?"
deck: 'compiler-implementation'
concepts:
  - fref("journeys/programming-language-theory/concepts/macro-system.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-3-syntactic-sugar.td")
---

::: flashcard
${question}
=== key
A language facility that provides programmable syntax transformations through macros.
:::
