---
_type: Flashcard
deck: 'pure-lambda-calculus'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
What's the difference between the fixed-point y-combinator and the fixed-point z-combinator?
=== key
- The Y-combinator is used in call-by-name languages.
- The Z-combinator is used in call-by-value languages.
:::
