---
_type: Flashcard
question: "What's the idea of axiomatic semantics?"
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/axiomatic-semantics.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
${question}
=== key
Define a language by its rules/laws instead of by how it runs or what it denotes.
:::
