---
_type: Flashcard
deck: 'logic-tools'
concepts:
  - fref("journeys/programming-language-theory/concepts/natural-deduction-style.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
What is the deduction style presentation of logical systems?
=== key
The premises are listed above the horizontal line & the conclusion is listed below the horizontal line.
:::
