---
_type: Flashcard
question: "What are some representations for natural numbers? what did we choose in rocq?"
deck: 'rocq-programming-language'
concepts:
  - fref("journeys/programming-language-theory/concepts/rocq.td")
  - fref("journeys/programming-language-theory/concepts/church-numeral.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
${question}
=== key
- Unary representation. -> Church numeral.
- Decimal representation.
- Hexadecimal representation.
- Octal representation.
- Binary representation.
:::
