---
_type: Flashcard
deck: 'type-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/language-safety.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
---

::: flashcard
What is the relation between language safety and partiality?
=== key
A safe language should have partial operations: `+` cannot work on strings for example.
:::
