---
_type: Flashcard
question: "What is operational semantics?"
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/operational-semantics.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
${question}
=== key
A style of semantics that defines a language by how it runs using syntactic transformation.
:::
