---
_type: Flashcard
question: "What is a powerset?"
deck: 'set-theory-relation'
concepts:
  - fref("journeys/programming-language-theory/concepts/powerset.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
---

::: flashcard
${question}
=== key
Given a set $S$, then $\mathcal{P}(S)$ is the set of all subsets of $S$.
:::
