---
_type: Flashcard
deck: 'programming-language-basic'
concepts:
  - fref("journeys/programming-language-theory/concepts/lexical-static-scope.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

::: flashcard
What is lexical/static scope?
=== key
Lexical/static scoping is a binding resolution strategy where a variable's binding is determined by its textual position in the source code.
:::
