---
_type: Flashcard
question: "What makes a type system sound?"
deck: 'type-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/safe-sound-type-system.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-1-introduction.td")
---

::: flashcard
${question}
=== key
A type system is sound if the claim they make about the program actually holds at runtime.
:::
