---
_type: Flashcard
deck: 'set-theory-relation'
concepts:
  - fref("journeys/programming-language-theory/concepts/backward-chaining-search.td")
  - fref("journeys/programming-language-theory/concepts/goal-directed.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
What are the pros and cons of backward chaining search?
=== key
Backward chaining search can eventually find a derivation for a derivable judgment, goal-directed.

Backward chaining search may fail to decide that a non-derivable judgment cannot be derived.
:::
