---
_type: Flashcard
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/method.td")
  - fref("journeys/programming-language-theory/concepts/function.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
---

::: flashcard
What is the relation between methods and functions?
=== key
A Method is a function that gets bound to an Object.
:::
