---
_type: Flashcard
question: "What's the relation between runtime errors and stuckness?"
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/pure-untyped-lambda-calculus.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
${question}
=== key
A runtime error is a state of an abstract machine in which a lambda term become stuck.
:::
