---
_type: Flashcard
question: "What are some problems with static types that make avoiding runtime errors impossible?"
deck: 'type-theory'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
---

::: flashcard
${question}
=== key
Types **abstract away** runtime details to provide guarantees statically.

-> Unable to guarantee within-bound constraints, etc.
:::
