---
_type: Flashcard
question: "What is aliasing?"
deck: 'programming-language-basic'
concepts:
  - fref("journeys/programming-language-theory/concepts/aliasing.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

::: flashcard
${question}
=== key
Aliasing is a phenomenon where multiple paths (variables, references, member accesses) refer to the same memory location.
:::
