---
_type: Flashcard
question: "When a rule is not an axiom, what is it called?"
deck: 'proof-technique'
concepts:
  - fref("journeys/programming-language-theory/concepts/axiom.td")
  - fref("journeys/programming-language-theory/concepts/rule.td")
  - fref("journeys/programming-language-theory/concepts/proper-rule.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
${question}
=== key
Proper rule.
:::
