---
_type: Flashcard
question: "Which special treatments are given to natural numbers in rocq?"
deck: 'rocq-programming-language'
concepts:
  - fref("journeys/programming-language-theory/concepts/church-numeral.td")
  - fref("journeys/programming-language-theory/concepts/rocq.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
${question}
=== key
Rocq gives natural numbers special parsing and printing capabilities.
:::
