---
_type: Flashcard
deck: 'pure-lambda-calculus'
concepts:
  - fref("journeys/programming-language-theory/concepts/pure-untyped-lambda-calculus.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
Which terms are deemed values in untyped lambda calculus?
=== key
Lambda abstractions/Functions are the only values.
:::
