---
_type: Flashcard
question: "Why are type systems a valuable maintenance tool?"
deck: 'type-theory'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-1-introduction.td")
---

::: flashcard
${question}
=== key
When you refactor, some function signatures or variables' types may change, a type system would catch most locations that the refactor may miss.
:::
