---
_type: Flashcard
question: "Why is forward chaining undirected?"
deck: 'proof-technique'
concepts:
  - fref("journeys/programming-language-theory/concepts/forward-chaining.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
${question}
=== key
Forward chaining just keeps track of a set of currently derived judgments and then expands its each step - oblivious of the goal.
:::
