---
_type: Flashcard
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/syntactic-sugar.td")
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-3-syntactic-sugar.td")
---

::: flashcard
Why is there a need for syntactic sugar?
=== key
- The core calculus can be minimal, so that proofs about them can be easily derived and the compiler implementation can be kept simple.
- The surface syntax can be more ergonomic for users & proofs about the surface language can be easily derived from the core calculus.
:::
