---
_type: Flashcard
question: "Why can there be nonsensical terms in the untyped calculus of booleans and numbers?"
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/untyped-calculus-of-booleans-and-numbers.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
${question}
=== key
There's no type system.
:::
