---
_type: Flashcard
deck: 'set-theory-relation'
concepts:
  - fref("journeys/programming-language-theory/concepts/backward-chaining-search.td")
  - fref("journeys/programming-language-theory/concepts/backward-chaining.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
Why is backward chaining goal-directed?
=== key
Because Backward chaining starts from the goal and works backwards towards the axioms.
:::
