---
_type: Flashcard
question: "Why is backward chaining goal-directed?"
deck: 'set-theory-relation'
concepts:
  - fref("journeys/programming-language-theory/concepts/backward-chaining-search.td")
  - fref("journeys/programming-language-theory/concepts/backward-chaining.td")
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
${question}
=== key
Because Backward chaining starts from the goal and works backwards towards the axioms.
:::
