---
_type: Flashcard
deck: 'language-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/operational-semantics.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
Why is it useful to give >= 2 operational semantics for a single language?
=== key
It's useful to give 2 operational semantics:

- One more abstract, with machine states that look similar to the terms that the programmer writes.
- Another closer to the structures manipulated by an actual interpreter or compiler for the language.
:::
