---
_type: Flashcard
question: "Why are most dynamically checked languages safe?"
deck: 'type-theory'
concepts:
  - fref("journeys/programming-language-theory/concepts/language-safety.td")
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-1-introduction.td")
---

::: flashcard
${question}
=== key
If a runtime provides any checking at all, it's trivial to provide the utmost safety.
:::
