---
_type: Flashcard
question: "Why is the property that static types are checked at compile-time is valuable?"
deck: 'type-theory'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
---

::: flashcard
${question}
=== key
- Programs may be expensive/unsafe/destructive to run.
- Runtime tests cannot cover all the state space.
:::
