---
_type: Flashcard
deck: 'language-theory'
books:
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
---

::: flashcard
According to robert (bob) harper, what is an operator, the arity of an operator?
=== key
An operator is a stand-in for an internal node's type of an abstract syntax tree.

The arity of an operator is basically its type signature, denoting the sort of the operator and the number and the sorts of its arguments.
:::
