---
_type: Flashcard
deck: 'language-theory'
concepts:
  - fref("programming-language-theory/concepts/normal-form.td")
  - fref("programming-language-theory/concepts/value.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
Are values always in normal form?
=== key
May not be, but should hold for all meaningful calculus.
:::
