---
_type: Flashcard
deck: 'compiler-implementation'
concepts:
  - fref("programming-language-theory/concepts/read-eval-print-loop-repl.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
---

::: flashcard
Does a REPL enforce a kind of implementation (compilation/interpretation)?
=== key
No. But mostly a REPL implements interpretation.
:::
