---
_type: Flashcard
_label: 'Functions that diverge vs functions that can fail?'
deck: 'set-theory-relation'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
---

::: flashcard
Functions that diverge vs functions that can fail?
=== key
A function $f$ fails at a value $x$ if $f(x) = \text{error}$, or $f(x) \uparrow$.

A function $f$ diverges at a value $x$ if it's not defined there.
:::
