---
_type: Flashcard
_label: 'Given an equivalence relation r, what does "up to r" mean?'
deck: 'set-theory-relation'
books:
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
---

::: flashcard
Given an equivalence relation r, what does "up to r" mean?
=== key
"Up to $R$" means that terms related by $R$ are treated indiscriminately.
:::
