---
_type: Flashcard
_label: 'How is a type checker different from a proof checker?'
deck: 'type-theory'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-1-introduction.td")
---

::: flashcard
How is a type checker different from a proof checker?
=== key
A type checker can be a proof checker. Theoretically,  a **full proof** that the program **meets some arbitrary specification** could be **encoded in type annotations**.
:::
