---
_type: Flashcard
_label: 'How are derivations visualized?'
deck: 'proof-technique'
concepts:
  - fref("programming-language-theory/concepts/derivation.td")
  - fref("programming-language-theory/concepts/derivation-tree.td")
books:
  - fref("programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
How are derivations visualized?
=== key
Derivation tree:

- The root is the desired judgment.
- Each node other than the root is an intermediate judgment.
- All the children of a node represent its premises.
:::
