---
_type: Flashcard
_label: 'How to merge multiple patterns in a match arm in rocq?'
deck: 'rocq-programming-language'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
How to merge multiple patterns in a match arm in rocq?
=== key
[course_late_policies.v (L12-L30)](https://github.com/huydo862003/type-theory/blob/543dabaefb5f1d7bad8cecbe8d8cc26aeda21a03/sf/lf/ch01-basics/exercises/course_late_policies.v#L12-L30)
:::
