---
_type: Flashcard
deck: 'language-theory'
concepts:
  - fref("programming-language-theory/concepts/valence.td")
books:
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
---

::: flashcard
In an ABT, what is the valence of an argument?
=== key
The specification of an argument of an operator, specifying the number and the sorts of its bound variables and the sort of itself.
:::
