---
_type: Flashcard
deck: 'pure-lambda-calculus'
concepts:
  - fref("programming-language-theory/concepts/lambda-calculus.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
In which ways the lambda calculus can be viewed?
=== key
- A **simple programming language** in which computations can be described.
- A **mathematical object** about which rigorous statements can be proved.
:::
