---
_type: Flashcard
deck: 'type-theory'
concepts:
  - fref("programming-language-theory/concepts/inheritance.td")
  - fref("programming-language-theory/concepts/subtyping.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
---

::: flashcard
Is inheritance = subtyping?
=== key
No.

Inheritance is to introduce subclassing, which is more about code reuse.

Subtyping is a static approximation to substitutability.
:::
