---
_type: Flashcard
_label: 'To understand how a program may misbehave in an unsafe language, what should the programmer do?'
deck: 'type-theory'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-1-introduction.td")
---

::: flashcard
To understand how a program may misbehave in an unsafe language, what should the programmer do?
=== key
Know about the internals of the runtime & the platform.
:::
