---
_type: Flashcard
_label: 'What are the pros of lightweight formal methods'
deck: 'language-theory'
concepts:
  - fref("programming-language-theory/concepts/type-system.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-1-introduction.td")
---

::: flashcard
What are the pros of lightweight formal methods
=== key
- Do not require high sophistication from the side of the programmer, more accessible.
- Practical.
:::
