---
_type: Flashcard
deck: 'programming-language-basic'
concepts:
  - fref("programming-language-theory/concepts/closure.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

::: flashcard
What is a closure in programming language?
=== key
A closure is a function that memorizes its surrounding environment, so i can access variables from the outside.
:::
