---
_type: Flashcard
deck: 'language-theory'
concepts:
  - fref("programming-language-theory/concepts/denotational-semantics.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
What's the idea of denotational semantics?
=== key
A style of semantics that compositionally defines the meaning of each term by mapping it into a mathematical object.
:::
