---
_type: Flashcard
_label: 'What is a desugarer?'
deck: 'compiler-implementation'
concepts:
  - fref("programming-language-theory/concepts/desugarer.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-3-syntactic-sugar.td")
---

::: flashcard
What is a desugarer?
=== key
A compiler phase or program that transforms syntactic sugar into core language constructs, typically running before interpretation or further compilation stages.
:::
