---
_type: Flashcard
deck: 'type-theory'
concepts:
  - fref("programming-language-theory/concepts/nominal-typing.td")
  - fref("programming-language-theory/concepts/structural-typing.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
---

::: flashcard
What are nominal typing and structural typing?
=== key
Nominal typing is a policy that determines type compatibility based on user-provided declarations.

Structural typing is a policy that determines type compatibility based on their structures.
:::
