---
_type: Flashcard
deck: 'logic-tools'
concepts:
  - fref("programming-language-theory/concepts/proof-assistant-prover.td")
books:
  - fref("programming-language-theory/books/software-foundations/logical-foundations.td")
---

::: flashcard
What are the pros and cons of proof assistants?
=== key
- Automated for routine tasks of building proofs.
- Require human guidance for more difficult aspects.
- In general more flexible than Automated theorem prover.
:::
