---
_type: Flashcard
_label: 'What are the approaches to implementing macros?'
deck: 'language-theory'
concepts:
  - fref("programming-language-theory/concepts/macro.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-3-syntactic-sugar.td")
---

::: flashcard
What are the approaches to implementing macros?
=== key
AST rewriting

Parenthetical language
:::
