---
_type: Flashcard
deck: 'language-theory'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
---

::: flashcard
What is an example for the tradeoffs between the type system's expressiveness & decidability?
=== key
Refined type: Allow the programmers to encode non-zeroness into the the type.

-> Typechecking becomes undecidable.
:::
