---
_type: Flashcard
deck: 'language-theory'
concepts:
  - fref("programming-language-theory/concepts/structural-induction.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
What is structural induction?
=== key
A proof technique that proves some property $P$ for a term $t$ by relying on the property $P$ holding for $t$'s subterms.
:::
