---
_type: Flashcard
_label: 'What is a fresh renaming?'
deck: 'language-theory'
concepts:
  - fref("programming-language-theory/concepts/fresh-renaming.td")
books:
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
---

::: flashcard
What is a fresh renaming?
=== key
Given a set of variables $\mathcal{X}$, a set of sorts $\mathcal{S}$, a sort-indexed family of $\mathcal{A} = \{\mathcal{A}_s\}$, then a Fresh renaming relative to $\mathcal{X}$ is a bijection $\rho : \vec{x} \leftrightarrow \vec{x}'$, such that $\vec{x} \notin \mathcal{X}$.
:::
