---
_type: Flashcard
_label: 'What is the relationship between a generic inductive definition and an ordinary inductive definition?'
deck: 'general'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-3-hypothetical-and-general-judgments.td")
---

::: flashcard
What is the relationship between a generic inductive definition and an ordinary inductive definition?
=== key
:::
