---
_type: Flashcard
_label: 'What is the main principle of functional programming?'
deck: 'language-theory'
concepts:
  - fref("programming-language-theory/concepts/functional-programming.td")
books:
  - fref("programming-language-theory/books/software-foundations/logical-foundations.td")
---

::: flashcard
What is the main principle of functional programming?
=== key
Computations should be as pure as possible: It only returns results based on its input, do not cause side effects.

- Easy to reason about.
- Interested in concurrent programming.
- A bridge between logic and programming.
:::
