---
_type: Flashcard
_label: 'What are the methods of finding derivations?'
deck: 'logic-tools'
concepts:
  - fref("programming-language-theory/concepts/forward-chaining.td")
books:
  - fref("programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
What are the methods of finding derivations?
=== key
- Forward chaining/Bottom-up construction

    Start with the set of axioms, and work towards the desired judgment.

- Backward chaining/Top-down construction

    Start with the desired judgment, and work backwards towards the axioms.
:::
