---
_type: Flashcard
deck: 'rocq-programming-language'
concepts:
  - fref("programming-language-theory/concepts/proof-by-rewriting.td")
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
What is proof by rewriting in rocq?
=== key
A proof by rewriting is a tactic that involves rewriting terms to terms that have been proven to be equal.
:::
