---
_type: Flashcard
deck: 'type-theory'
concepts:
  - fref("programming-language-theory/concepts/type-system.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-1-introduction.td")
---

::: flashcard
What else can a type system catch other than low-level faults such as invoking non-existent methods
=== key
- Access control.
- Arbitrary constraints.
:::
