---
_type: Flashcard
_label: 'What is the relation between types and runtime values?'
deck: 'type-theory'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
---

::: flashcard
What is the relation between types and runtime values?
=== key
Type is a static approximation of the runtime behavior of values computed by a term.
:::
