---
_type: Flashcard
_label: 'What are the pros and cons of forward chaining search?'
deck: 'proof-technique'
concepts:
  - fref("programming-language-theory/concepts/forward-chaining.td")
books:
  - fref("programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
What are the pros and cons of forward chaining search?
=== key
Quite similar to What are the pros and cons of backward chaining search?, except that forward chaining search is undirected
:::
