---
_type: Flashcard
_label: 'What does the transition function do in the structural operational semantics?'
deck: 'language-theory'
concepts:
  - fref("programming-language-theory/concepts/small-step-structural-operational-semantics-sos.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
What does the transition function do in the structural operational semantics?
=== key
Describe the machine's behavior - for each state, either:

- Gives the next state by performing a step of **simplification** on the term.
- Declares that the machine has **halted**.
:::
