---
_type: Flashcard
_label: 'What is the idea of mixins?'
deck: 'type-theory'
concepts:
  - fref("programming-language-theory/concepts/mixin.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
---

::: flashcard
What is the idea of mixins?
=== key
Mixin intends to provide the same code reuse capability as inheritance, but with only the class extension, not bound to a specific superclass. This allows for good abstraction & reusability.
:::
