---
_type: Flashcard
_label: 'What is the wildcard pattern in rocq?'
deck: 'rocq-programming-language'
concepts:
  - fref("programming-language-theory/concepts/rocq.td")
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
What is the wildcard pattern in rocq?
=== key
The wildcard pattern `_` allows matching all values without introducing unnecessary variables.
:::
