---
_type: Flashcard
deck: 'rocq-programming-language'
concepts:
  - fref("programming-language-theory/concepts/proof-by-simplification.td")
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
What are simpl, reflexivity in rocq?
=== key
Two proof tactics that relates to Proof by simplification, that is, they both try to unfold the terms then evaluate the expressions.
:::
