---
_type: Flashcard
_label: 'What is the relation between "meaning" and "representation"?'
deck: 'language-theory'
concepts:
  - fref("programming-language-theory/concepts/representation.td")
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
What is the relation between "meaning" and "representation"?
=== key
- One representation can have multiple meanings, depending on its usage.
- One meaning can have multiple representation.
:::
