---
_type: Flashcard
deck: 'pure-lambda-calculus'
concepts:
  - fref("programming-language-theory/concepts/lambda-calculus.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
What does it mean by "everything is a function" in lambda calculus?
=== key
Every closed terms in Lambda calculus are functions.
:::
