---
_type: Flashcard
_label: 'What is garbage collection?'
deck: 'programming-language-basic'
concepts:
  - fref("programming-language-theory/concepts/garbage-collection.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

::: flashcard
What is garbage collection?
=== key
Garbage collection is a runtime mechanism that utilizes a heuristic to detect and release no-longer-used memory.
:::
