---
_type: Flashcard
_label: 'What is a fresh variable (concerning a set of variables)?'
deck: 'language-theory'
concepts:
  - fref("programming-language-theory/concepts/fresh-variable.td")
  - fref("programming-language-theory/concepts/abstract-syntax-tree-ast.td")
books:
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
---

::: flashcard
What is a fresh variable (concerning a set of variables)?
=== key
A variable is fresh in a variable set $\mathcal{X}$ if it's not within $\mathcal{X}$.
:::
