---
_type: Flashcard
_label: 'What is the idea of JIT compilation?'
deck: 'compiler-implementation'
concepts:
  - fref("programming-language-theory/concepts/just-in-time-jit-compilation.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
---

::: flashcard
What is the idea of JIT compilation?
=== key
A hybrid approach where programs are interpreted, but code is monitored for hot areas and compiled away to binary.
:::
