---
_type: Flashcard
deck: 'language-theory'
concepts:
  - fref("programming-language-theory/concepts/object.td")
  - fref("programming-language-theory/concepts/closure.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
---

::: flashcard
What is the relation between objects and closures?
=== key
An Object is a Closure with multiple entrypoints.
:::
