---
_type: Flashcard
_label: 'What are the 2 definitions of substitution used in TAPL? for what purposes?'
deck: 'pure-lambda-calculus'
concepts:
  - fref("programming-language-theory/concepts/capture-avoiding-substitution.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
What are the 2 definitions of substitution used in TAPL? for what purposes?
=== key
- $[x \to s]t$ -> Useful for mathematical reasoning, proofs.
- De Bruijn's notation -> Notationally heavier, but useful for compiler's implementation.
:::
