---
_type: Flashcard
deck: 'compiler-implementation'
concepts:
  - fref("programming-language-theory/concepts/read-eval-print-loop-repl.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
---

::: flashcard
What is an REPL?
=== key
A program that provides an interactive interface for programmers to interact with a programming language in an adhoc and highly-responsive fashion. The name represents the typical phases of this interaction: The program reads the input from the user, evaluates it, prints out the result and loops.
:::
