---
_type: Flashcard
_label: 'What are the key considerations in designing conditionals?'
deck: 'compiler-implementation'
concepts:
  - fref("programming-language-theory/concepts/conditional-expression.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
---

::: flashcard
What are the key considerations in designing conditionals?
=== key
- Which data types are allowed in conditionals?

    Which values are truthy and falsy?

- How to handle diverging datatypes of `then` and `else` expressions.
:::
