---
_type: Flashcard
_label: 'Which values are truthy in rocq?'
deck: 'rocq-programming-language'
concepts:
  - fref("programming-language-theory/concepts/rocq.td")
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
Which values are truthy in rocq?
=== key
The first constructor of an inductive type that has two constructors.
:::
