---
_type: Flashcard
_label: 'Which symbol is used to denote pure lambda calculus?'
deck: 'pure-lambda-calculus'
concepts:
  - fref("programming-language-theory/concepts/pure-untyped-lambda-calculus.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
Which symbol is used to denote pure lambda calculus?
=== key
$\to$
:::
