---
_type: Flashcard
deck: 'proof-technique'
concepts:
  - fref("programming-language-theory/concepts/forward-chaining.td")
books:
  - fref("programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
Why is forward chaining undirected?
=== key
Forward chaining just keeps track of a set of currently derived judgments and then expands its each step - oblivious of the goal.
:::
