---
_type: Book
_label: 'Software Design X-Rays: Fix Technical Debt with Behavioral Code Analysis '
date: '2018'
journey: fref("software-engineering/index.td")
description: 'Introduce human-centered pragmatic behavioral code analysis practices (mostly dynamic) as opposed to static analysis.'
isbn: '9781680502725'
url: "https://pragprog.com/titles/atevol/software-design-x-rays/"
cover: fref("software-engineering/books/software-design-xray/assets/software-design-xray-cover.jpg")
tags:
 - 'Software design'
---
