---
_type: PltFlashcard
_label: 'According to robert (bob) harper, what is the scope of a binding?'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/binding.td")
books:
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
---

::: flashcard
According to robert (bob) harper, what is the scope of a binding?
=== key
The scope of a binding is an ABT in which the corresponding bound identifier can be used as a placeholder or an index of an indexed operator.
:::
