---
_type: PltFlashcard
_label: 'According to robert (bob) harper, what is a variable?'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/variable.td")
books:
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
---

::: flashcard
According to robert (bob) harper, what is a variable?
=== key
An unknown object drawn from a specific domain. In the context of Chapter 1. Abstract syntax, it's the placeholder for an AST of a given sort.
:::
