---
_type: PltFlashcard
_label: 'Are normal forms always a value?'
deck: 'pure-lambda-calculus'
concepts:
  - fref("programming-language-theory/concepts/value.td")
  - fref("programming-language-theory/concepts/normal-form.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
Are normal forms always a value?
=== key
Normal forms can be stuck terms.
:::
