---
_type: PltFlashcard
_label: 'Are there many built-in features in rocq?'
deck: 'rocq-programming-language'
concepts:
  - fref("programming-language-theory/concepts/rocq.td")
books:
  - fref("programming-language-theory/books/software-foundations/01-logical-foundations/01-chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
Are there many built-in features in rocq?
=== key
The Rocq's Gallina is a small but expressive functional language.
:::
