---
_type: PltFlashcard
_label: 'Are there booleans, strings, numbers defined in rocq?'
deck: 'rocq-programming-language'
concepts:
  - fref("programming-language-theory/concepts/rocq.td")
books:
  - fref("programming-language-theory/books/software-foundations/01-logical-foundations/01-chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
Are there booleans, strings, numbers defined in rocq?
=== key
Everything can be defined from scratch and there are no built-in boolean, string or number. However, the standard library still includes those.
:::
