---
_type: PltFlashcard
_label: 'Between if-splitting and conditionals, which one can introduce unions, which one eliminates?'
deck: 'type theory'
concepts:
  - fref("programming-language-theory/concepts/if-splitting.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
---

::: flashcard
Between if-splitting and conditionals, which one can introduce unions, which one eliminates?
=== key
- If-splittings eliminate union types.
- Conditionals introduce union types.
:::
