---
_type: PltFlashcard
_label: 'Can a term fall within multiple syntactic categories?'
deck: 'pure-lambda-calculus'
concepts:
  - fref("programming-language-theory/concepts/pure-untyped-lambda-calculus.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
Can a term fall within multiple syntactic categories?
=== key
Yes.
:::
