---
_type: PltFlashcard
_label: 'Can the type system totally not require interaction with or guidance from the programmers?'
deck: 'type theory'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-1-introduction.td")
---

::: flashcard
Can the type system totally not require interaction with or guidance from the programmers?
=== key
It may, but sometimes, the programmer can provide guidance by giving type annotations.
:::
