---
_type: Flashcard
_label: 'Does a language specify how it should be evaluated?'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/compiler.td")
  - fref("programming-language-theory/concepts/interpreter.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
---

::: flashcard
Does a language specify how it should be evaluated?
=== key
No.
:::
