---
_type: Flashcard
_label: 'How to place declarations inside a module in rocq?'
deck: 'rocq-programming-language'
concepts:
  - fref("programming-language-theory/concepts/rocq.td")
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
How to place declarations inside a module in rocq?
=== key
Wrap the declarations inside: `Module X.` and `End X.`
:::
