---
_type: Flashcard
_label: 'How to use inductive definition to define functions?'
deck: 'logic tools'
concepts:
  - fref("programming-language-theory/concepts/inductive-definition.td")
  - fref("programming-language-theory/concepts/function.td")
books:
  - fref("programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
How to use inductive definition to define functions?
=== key
- Define a relation between inputs and outputs of the function using Inductive definition.
- Then prove that for each set of inputs, the output is unique.
:::
