---
_type: PltFlashcard
_label: 'How to introduce infix syntax in rocq?'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/infix.td")
books:
  - fref("programming-language-theory/books/software-foundations/01-logical-foundations/01-chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
How to introduce infix syntax in rocq?
=== key
Use `Notation "x <op> y" := exp`.
:::
