---
_type: PltFlashcard
_label: 'How does the principle of rule induction apply to the case simultaneous inductive definitions?'
deck: 'proof technique'
concepts:
  - fref("programming-language-theory/concepts/simultaneous-inductive-definition.td")
books:
  - fref("programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
How does the principle of rule induction apply to the case simultaneous inductive definitions?
=== key
Same as for Iterated inductive definition, just that we simultaneously handle more than one properties for more than one judgment forms.
:::
