---
_type: PltFlashcard
_label: 'How to encode multiple arguments in lambda calculus?'
deck: 'pure-lambda-calculus'
concepts:
  - fref("programming-language-theory/concepts/pure-untyped-lambda-calculus.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
How to encode multiple arguments in lambda calculus?
=== key
Use currying.
:::
