---
_type: PltFlashcard
_label: 'How is the type "bool -> bool" pronounced in rocq?'
deck: 'rocq-programming-language'
concepts:
  - fref("programming-language-theory/concepts/rocq.td")
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
How is the type "bool -> bool" pronounced in rocq?
=== key
"bool arrow bool".
:::
