---
_type: Flashcard
_label: 'In an unsafe language, how can the system be disrupted?'
deck: 'type theory'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-1-introduction.td")
---

::: flashcard
In an unsafe language, how can the system be disrupted?
=== key
For example, an unsafe language like C can run into buffer overrun attack, allowing an erroneous program to modify arbitrary memory.
:::
