---
_type: Flashcard
_label: 'In how many stages does the transformation from concrete syntax to abstract syntax undergo?'
deck: 'compiler implementation'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
In how many stages does the transformation from concrete syntax to abstract syntax undergo?
=== key
- Lexical analysis.
- Parsing.
:::
