---
_type: PltFlashcard
_label: 'In pure lambda calculus, what are the built-in constants and primitive operators?'
deck: 'pure-lambda-calculus'
concepts:
  - fref("programming-language-theory/concepts/pure-untyped-lambda-calculus.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
In pure lambda calculus, what are the built-in constants and primitive operators?
=== key
- No operator.
- Only lambda abstraction.
:::
