---
_type: Flashcard
_label: 'In which style do the inductive definition and the inference rule format describe the syntax of a language?'
deck: 'logic tools'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
In which style do the inductive definition and the inference rule format describe the syntax of a language?
=== key
Non-constructive.
:::
