---
_type: PltFlashcard
_label: 'Is bullet point optional in subgoals in a destruct tactic? if yes, why would you use it?'
deck: 'general'
books:
  - fref("programming-language-theory/books/software-foundations/01-logical-foundations/01-chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
Is bullet point optional in subgoals in a destruct tactic? if yes, why would you use it?
=== key
:::
