---
_type: PltFlashcard
_label: 'Language safety from the perspective of trapped and untrapped errors?'
deck: 'language theory'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-1-introduction.td")
---

::: flashcard
Language safety from the perspective of trapped and untrapped errors?
=== key
Trapped error: An error that causes immediate termination of the process.

Untrapped error: An error that does not cause immediate termination of the process, possibly corrupting it.

A safe language is one that does not have untrapped errors.
:::
