---
_type: PltFlashcard
_label: 'Name some lightweight formal methods'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/type-system.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-1-introduction.td")
---

::: flashcard
Name some lightweight formal methods
=== key
- Model checker.
- Type system.
- Runtime monitoring.
:::
