---
_type: Flashcard
_label: 'The relation between the set of values and the set of terms?'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/term.td")
  - fref("programming-language-theory/concepts/value.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
The relation between the set of values and the set of terms?
=== key
The set of values is a subset of the set of terms.
:::
