---
_type: PltFlashcard
_label: 'The definition of type system'
deck: 'type theory'
concepts:
  - fref("programming-language-theory/concepts/type-system.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-1-introduction.td")
---

::: flashcard
The definition of type system
=== key
Type system is a **tractable syntactic method** to **prove the absence of a program's behavior** by **classifying phrases according to the types of values they compute**.
:::
