---
_type: PltFlashcard
_label: 'The definition of runtime type error'
deck: 'type theory'
concepts:
  - fref("programming-language-theory/concepts/runtime-type-error.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-1-introduction.td")
---

::: flashcard
The definition of runtime type error
=== key
Runtime type error is the class of program behaviors that a specific type system is designed to eliminate.
:::
