---
_type: PltFlashcard
_label: 'What are lambda terms and lambda abstractions?'
deck: 'pure-lambda-calculus'
concepts:
  - fref("programming-language-theory/concepts/lambda-calculus.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
What are lambda terms and lambda abstractions?
=== key
Lambda terms are any syntactic constructs in Lambda calculus.

Lambda abstractions are lambda terms of the form $\lambda x.\ \text{term}$.
:::
