---
_type: PltFlashcard
_label: 'What do programming languages describe, and for whom?'
deck: 'programming-language-basic'
books:
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/01-part-i-judgments-and-rules/01-chapter-1-abstract-syntax.td")
---

::: flashcard
What do programming languages describe, and for whom?
=== key
Programming languages describe computations to human and machines.
:::
