---
_type: Flashcard
_label: 'What is a block in programming language?'
deck: 'programming-language-basic'
concepts:
  - fref("programming-language-theory/concepts/block.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

::: flashcard
What is a block in programming language?
=== key
A block is a syntactic construct that groups statements and introduces a scope for local variables.
:::
