---
_type: PltFlashcard
_label: 'What is usually meant by substitution?'
deck: 'pure-lambda-calculus'
concepts:
  - fref("programming-language-theory/concepts/capture-avoiding-substitution.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
What is usually meant by substitution?
=== key
Capture-avoiding substitution
:::
