---
_type: PltFlashcard
_label: 'What is an object?'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/object.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
---

::: flashcard
What is an object?
=== key
- A value that maps names to stuff (either other values or "methods").
- A generalization of Closures.
:::
