---
_type: PltFlashcard
_label: 'What is an abstract binding graph (ABG)?'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/abstract-binding-graph.td")
books:
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/01-part-i-judgments-and-rules/01-chapter-1-abstract-syntax.td")
---

::: flashcard
What is an abstract binding graph (ABG)?
=== key
:::
