---
_type: Flashcard
_label: 'What are substitution target and subject?'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/substitution-subject.td")
  - fref("programming-language-theory/concepts/substitution-target.td")
books:
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
---

::: flashcard
What are substitution target and subject?
=== key
Substitution target: The target term into which variables are substituted.

Substitution subject: The variable that is substituted.
:::
