---
_type: Flashcard
_label: 'What is a macro system?'
deck: 'compiler implementation'
concepts:
  - fref("programming-language-theory/concepts/macro-system.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-3-syntactic-sugar.td")
---

::: flashcard
What is a macro system?
=== key
A language facility that provides programmable syntax transformations through macros.
:::
