---
_type: PltFlashcard
_label: 'What is the class pattern?'
deck: 'language theory'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
---

::: flashcard
What is the class pattern?
=== key
Simple class pattern:

```racket
(define (cls args)
	(lambda (m)
		(case (m)
			[]
			[])))
```

What is the class pattern with private members?

What is the class pattern with both private members and static members?
:::
