---
_type: Flashcard
_label: 'What are combinators in lambda calculus?'
deck: 'pure-lambda-calculus'
concepts:
  - fref("programming-language-theory/concepts/combinator.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
What are combinators in lambda calculus?
=== key
A term with no free variables.
:::
