---
_type: PltFlashcard
_label: 'What does it mean to say church numerals represent ordinary numbers?'
deck: 'pure-lambda-calculus'
concepts:
  - fref("programming-language-theory/concepts/church-numeral.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
What does it mean to say church numerals represent ordinary numbers?
=== key
Any programs written using numbers, assuming they are truly ordinary numbers, can have their numbers and associated operations substituted with Church numerals and their corresponding operations, without any changes in the observable behavior. -> Behavioral/Observational/Contextual equivalence.
:::
