---
_type: Flashcard
_label: 'What''s the downfall of denotational semantics?'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/denotational-semantics.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
What's the downfall of denotational semantics?
=== key
Concurrency.
:::
