---
_type: PltFlashcard
_label: 'What''s the relation between runtime errors and stuckness?'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/pure-untyped-lambda-calculus.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
What's the relation between runtime errors and stuckness?
=== key
A runtime error is a state of an abstract machine in which a lambda term become stuck.
:::
