---
_type: Flashcard
_label: 'What are computation and congruence rules?'
deck: 'logic tools'
concepts:
  - fref("programming-language-theory/concepts/computation-rule.td")
  - fref("programming-language-theory/concepts/congruence-rule.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
What are computation and congruence rules?
=== key
A computation rule directly reduces the current term.

A congruence rule delegate evaluation to another rule.
:::
