---
_type: Flashcard
_label: 'What is an instance of an inference rule?'
deck: 'logic tools'
concepts:
  - fref("programming-language-theory/concepts/instance-of-an-inference-rule.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
What is an instance of an inference rule?
=== key
An inference rule whose metavariables are replaced with real values.
:::
