---
_type: PltFlashcard
_label: 'What is the difference between a formal derivability judgment and a derivability judgment?'
deck: 'general'
books:
  - fref("programming-language-theory/books/software-foundations/01-logical-foundations/03-chapter-3-hypothetical-and-general-judgments.td")
---

::: flashcard
What is the difference between a formal derivability judgment and a derivability judgment?
=== key
:::
