---
_type: PltFlashcard
_label: 'What''s the strength of axiomatic semantics?'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/axiomatic-semantics.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
What's the strength of axiomatic semantics?
=== key
The proof rules/laws are of the fore-front focus.
:::
