---
_type: PltFlashcard
_label: 'What does "variables in an AST range over some specified sorts" mean?'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/variable.td")
books:
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
---

::: flashcard
What does "variables in an AST range over some specified sorts" mean?
=== key
Variables are placeholders for ASTs of some specified sorts.
:::
