---
_type: PltFlashcard
_label: 'What are some problems with static types that make avoiding runtime errors impossible?'
deck: 'type theory'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
---

::: flashcard
What are some problems with static types that make avoiding runtime errors impossible?
=== key
Types **abstract away** runtime details to provide guarantees statically.

-> Unable to guarantee within-bound constraints, etc.
:::
