---
_type: PltFlashcard
_label: 'What''s the symbol for untyped lambda calculus?'
deck: 'pure-lambda-calculus'
concepts:
  - fref("programming-language-theory/concepts/pure-untyped-lambda-calculus.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
What's the symbol for untyped lambda calculus?
=== key
$\to$
:::
