---
_type: PltFlashcard
_label: 'What is automatic memory management?'
deck: 'programming-language-basic'
concepts:
  - fref("programming-language-theory/concepts/automatic-memory-management.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

::: flashcard
What is automatic memory management?
=== key
Automatic memory management is a set of compile-time or dynamic techniques that allows the dynamic allocation and deallocation of memory without explicit instructions from the programmer.
:::
