---
_type: PltFlashcard
_label: 'What are the two broad categories of software tools for helping constructs proofs of logical propositions?'
deck: 'general'
books:
  - fref("programming-language-theory/books/software-foundations/01-logical-foundations/index.td")
---

::: flashcard
What are the two broad categories of software tools for helping constructs proofs of logical propositions?
=== key
:::
