---
_type: PltFlashcard
_label: 'What is the relation between methods and functions?'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/method.td")
  - fref("programming-language-theory/concepts/function.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
---

::: flashcard
What is the relation between methods and functions?
=== key
A Method is a function that gets bound to an Object.
:::
