---
_type: PltFlashcard
_label: 'What''s the difference between constructors and functions in rocq?'
deck: 'rocq-programming-language'
concepts:
  - fref("programming-language-theory/concepts/rocq.td")
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
What's the difference between constructors and functions in rocq?
=== key
Constructors have no notion of computation i.e. it has no computation rules.

Functionss ave computation rules.
:::
