---
_type: PltFlashcard
_label: 'What is a congruence?'
deck: 'set theory relation'
concepts:
  - fref("programming-language-theory/concepts/congruence.td")
books:
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/01-part-i-judgments-and-rules/01-chapter-1-abstract-syntax.td")
---

::: flashcard
What is a congruence?
=== key
An equivalence relation that is preserved under a specific operation.
:::
