---
_type: PltFlashcard
_label: 'What''s the standard notation for reflexive and transitive closure?'
deck: 'set theory relation'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
---

::: flashcard
What's the standard notation for reflexive and transitive closure?
=== key
For a relation $R$, then the reflexive and transitive closure of $R$ is denoted as $R^*$.
:::
