---
_type: Flashcard
_label: 'What is the difference between formal and actual parameters?'
deck: 'programming-language-basic'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

::: flashcard
What is the difference between formal and actual parameters?
=== key
- Formal parameter: The function parameters as defined in the function headers.
- Actual parameter: The function arguments.
:::
