---
_type: PltFlashcard
_label: 'What is the difference between the implicit and explicit form of a generic rule in a generic inductive definition?'
deck: 'general'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-3-hypothetical-and-general-judgments.td")
---

::: flashcard
What is the difference between the implicit and explicit form of a generic rule in a generic inductive definition?
=== key
:::
