---
_type: PltFlashcard
_label: 'What are the ideal use cases of ASTs?'
deck: 'compiler implementation'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
What are the ideal use cases of ASTs?
=== key
- **Formal language definitions** and **proofs** about languages.
- The internal workings of **compilers** and **interpreters**, which need to manipulate program structure precisely.
:::
