---
_type: Flashcard
_label: 'What is an environment in programming language?'
deck: 'programming-language-basic'
concepts:
  - fref("programming-language-theory/concepts/environment.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

::: flashcard
What is an environment in programming language?
=== key
An environment can be a theoretic construct to store bindings of variables to values/types as part of semantic/type-theoretic reasoning.

An environment can be a runtime data structure that store bindings of variables currently in scope to their values.
:::
