---
_type: Flashcard
_label: 'What is a rule scheme?'
deck: 'logic tools'
concepts:
  - fref("programming-language-theory/concepts/inference-rule.td")
  - fref("programming-language-theory/concepts/metavariable.td")
books:
  - fref("programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
What is a rule scheme?
=== key
Synonymous with Rule schema - An Inference rule that is parameterized with Metavariables.
:::
