---
_type: Flashcard
_label: 'What are some examples of automated theorem provers?'
deck: 'compiler implementation'
concepts:
  - fref("programming-language-theory/concepts/automated-theorem-prover.td")
  - fref("programming-language-theory/concepts/sat-solver.td")
  - fref("programming-language-theory/concepts/smt-solver.td")
books:
  - fref("programming-language-theory/books/software-foundations/logical-foundations.td")
---

::: flashcard
What are some examples of automated theorem provers?
=== key
- SAT solver
- SMT solver
- Model checker
:::
