---
_type: Flashcard
_label: 'What are the structural properties of generic derivability judgment, governing the behavior of variables, if the rules are uniform?'
deck: 'general'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-3-hypothetical-and-general-judgments.td")
---

::: flashcard
What are the structural properties of generic derivability judgment, governing the behavior of variables, if the rules are uniform?
=== key
:::
