---
_type: PltFlashcard
_label: 'What are the ideas of forward chaining and backward chaining?'
deck: 'proof technique'
concepts:
  - fref("programming-language-theory/concepts/forward-chaining.td")
books:
  - fref("programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
What are the ideas of forward chaining and backward chaining?
=== key
Forward chaining

Backward chaining
:::
