---
_type: Flashcard
_label: 'What is a metatheory?'
deck: 'other mathematics'
concepts:
  - fref("programming-language-theory/concepts/metatheory.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
What is a metatheory?
=== key
The study about properties of a formal system, using external reasonings.
:::
