---
_type: PltFlashcard
_label: 'What is the name of rocq''s native functional programming language?'
deck: 'rocq-programming-language'
concepts:
  - fref("programming-language-theory/concepts/rocq.td")
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
What is the name of rocq's native functional programming language?
=== key
Gallina.
:::
