---
_type: Flashcard
_label: 'What is recursive let?'
deck: 'programming-language-basic'
concepts:
  - fref("programming-language-theory/concepts/recursive-let.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

::: flashcard
What is recursive let?
=== key
Recursive let is a syntactic construct in Scheme in which each binding in the let definition is visible anywhere within the let expression.
:::
