---
_type: Flashcard
_label: 'What are some senses of the word "functional" in "functional programming"?'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/functional-programming.td")
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
What are some senses of the word "functional" in "functional programming"?
=== key
- Mathematical functions: To denote the resemblance to "pure" mathematical functions.
- Functions as first-class values.
:::
