---
_type: PltFlashcard
_label: 'What is the syntax for multi-argument application in rocq?'
deck: 'rocq-programming-language'
concepts:
  - fref("programming-language-theory/concepts/rocq.td")
books:
  - fref("programming-language-theory/books/software-foundations/01-logical-foundations/01-chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
What is the syntax for multi-argument application in rocq?
=== key
`(fn arg1 arg2 ...)`.
:::
