---
_type: Flashcard
_label: 'What is a metalanguage?'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/metalanguage.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
What is a metalanguage?
=== key
The language used to describe, define, or reason about another language.
:::
