---
_type: Flashcard
_label: 'What is a metavariable?'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/metavariable.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
What is a metavariable?
=== key
A variable of the metalanguage that ranges over terms of a syntactic category.
:::
