---
_type: Flashcard
_label: 'What is a rule schema and its relation with concrete rules?'
deck: 'logic tools'
concepts:
  - fref("programming-language-theory/concepts/inference-rule.td")
  - fref("programming-language-theory/concepts/instance-of-an-inference-rule.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
What is a rule schema and its relation with concrete rules?
=== key
A rule schema is synonymous with inference rule, representing a generic rule with metavariables.

A concrete rule is an instance of a rule schema.
:::
