---
_type: PltFlashcard
_label: 'What is a macro?'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/macro.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-3-syntactic-sugar.td")
---

::: flashcard
What is a macro?
=== key
Macro is a syntactic pattern that gets expanded into other code at compile time.
:::
