---
_type: Flashcard
_label: 'What does it mean by the judgment $gamma dash_mathcal{r} k$, where $gamma$ is a finite set of basic judgments, $k$ is a basic judgment and $mathcal{r}$ is a set of rules?'
deck: 'general'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-3-hypothetical-and-general-judgments.td")
---

::: flashcard
What does it mean by the judgment $\gamma \vdash_\mathcal{r} k$, where $\gamma$ is a finite set of basic judgments, $k$ is a basic judgment and $\mathcal{r}$ is a set of rules?
=== key
:::
