---
_type: PltFlashcard
_label: 'What is an axiom (inference rule)?'
deck: 'logic tools'
concepts:
  - fref("programming-language-theory/concepts/inference-rule.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/03-part-i-untyped-systems/01-chapter-3-untyped-arithmetic-expressions.td")
  - fref("programming-language-theory/books/software-foundations/01-logical-foundations/02-chapter-2-inductive-definitions.td")
---

::: flashcard
What is an axiom (inference rule)?
=== key
An axiom is an inference rule with no premise.
:::
