---
_type: PltFlashcard
_label: 'What does an inductive definition in rocq do?'
deck: 'rocq-programming-language'
concepts:
  - fref("programming-language-theory/concepts/rocq.td")
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
What does an inductive definition in rocq do?
=== key
It allows defining Algebraic data types in Rocq, including Recursive types.

Its name bears resemblance to Inductive definition.
:::
