---
_type: PltFlashcard
_label: 'What does lambda calculus consist of in its purest form?'
deck: 'pure-lambda-calculus'
concepts:
  - fref("programming-language-theory/concepts/lambda-calculus.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/03-part-i-untyped-systems/03-chapter-5-the-untyped-pure-lambda-calculus.td")
---

::: flashcard
What does lambda calculus consist of in its purest form?
=== key
- Function definition.
- Function application.
:::
