---
_type: Flashcard
_label: 'What are some ways to define the syntax of a language?'
deck: 'compiler implementation'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
What are some ways to define the syntax of a language?
=== key
- Inductive definition.
- 2-dimension inference rule format.
- Concrete generator style.
:::
