---
_type: Flashcard
_label: 'What are iterated and simultaneous inductive definition?'
deck: 'set-theory-relation'
concepts:
  - fref("programming-language-theory/concepts/simultaneous-inductive-definition.td")
books:
  - fref("programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
What are iterated and simultaneous inductive definition?
=== key
:::
