---
_type: PltFlashcard
_label: 'What is a powerset?'
deck: 'set theory relation'
concepts:
  - fref("programming-language-theory/concepts/powerset.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
---

::: flashcard
What is a powerset?
=== key
Given a set $S$, then $\mathcal{P}(S)$ is the set of all subsets of $S$.
:::
