---
_type: PltFlashcard
_label: 'What are there in the rocq system besides the kernel?'
deck: 'rocq-programming-language'
concepts:
  - fref("programming-language-theory/concepts/rocq.td")
  - fref("programming-language-theory/concepts/tactic.td")
books:
  - fref("programming-language-theory/books/software-foundations/logical-foundations.td")
---

::: flashcard
What are there in the rocq system besides the kernel?
=== key
- A large library of common definitions and axioms.
- Powerful tactics for constructing complex proofs semi-automatically.
- A special-purpose programming language for defining new proof-automation tactics for specific situations.
:::
