---
_type: PltFlashcard
_label: 'What if some hypotheses are not derivable relative to $mathcal{r}$, then what do we deem the corresponding admissibility judgment as?'
deck: 'general'
books:
  - fref("programming-language-theory/books/software-foundations/01-logical-foundations/03-chapter-3-hypothetical-and-general-judgments.td")
---

::: flashcard
What if some hypotheses are not derivable relative to $\mathcal{r}$, then what do we deem the corresponding admissibility judgment as?
=== key
:::
