---
_type: Flashcard
_label: 'What is the meaning of a term?'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/term.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
What is the meaning of a term?
=== key
The meaning of a term can be taken to be the final state of the abstract machine running it.
:::
