---
_type: PltFlashcard
_label: 'What is the operational semantics of boolean expressions?'
deck: 'pure-lambda-calculus'
concepts:
  - fref("programming-language-theory/concepts/untyped-calculus-of-booleans-and-numbers.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
What is the operational semantics of boolean expressions?
=== key
What is the operational semantics of arithmetic expressions?
:::
