---
_type: PltFlashcard
_label: 'What is an abstract binding tree (ABT)?'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/abstract-binding-tree-abt.td")
  - fref("programming-language-theory/concepts/valence.td")
  - fref("programming-language-theory/concepts/abstractor.td")
books:
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
---

::: flashcard
What is an abstract binding tree (ABT)?
=== key
An AST that is enriched with bindings and scopes.

Regarding Programming languages: Application and Interpretation:

- Each operator's arity now has its arguments with some valences.
- Each operator's arguments now become Abstractors.
:::
