---
_type: PltFlashcard
_label: 'What are the cons of lightweight formal methods'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/type-system.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/01-chapter-1-introduction.td")
---

::: flashcard
What are the cons of lightweight formal methods
=== key
Not as strong or general as more heavy-weight methods.
:::
