---
_type: PltFlashcard
_label: 'What can a hypothetical inductive definition be ragarded as an ordinary inductive definition of?'
deck: 'general'
books:
  - fref("programming-language-theory/books/software-foundations/01-logical-foundations/03-chapter-3-hypothetical-and-general-judgments.td")
---

::: flashcard
What can a hypothetical inductive definition be ragarded as an ordinary inductive definition of?
=== key
:::
