---
_type: PltFlashcard
_label: 'What does the admitted command do in rocq?'
deck: 'rocq-programming-language'
concepts:
  - fref("programming-language-theory/concepts/rocq.td")
books:
  - fref("programming-language-theory/books/software-foundations/01-logical-foundations/01-chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
What does the admitted command do in rocq?
=== key
It tells Rocq to just treat something as an Axiom.
:::
