---
_type: Flashcard
_label: 'What are the differences between terms and expressions?'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/term.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
What are the differences between terms and expressions?
=== key
Expression is used to denote any syntactic constructs.

Term is used to denote syntactic constructs that represents computation.
:::
