---
_type: PltFlashcard
_label: 'What is the syntax for imports in rocq?'
deck: 'rocq-programming-language'
concepts:
  - fref("programming-language-theory/concepts/import.td")
  - fref("programming-language-theory/concepts/require.td")
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

::: flashcard
What is the syntax for imports in rocq?
=== key
`From Library Require [Import] Module.`
:::
