---
_type: PltFlashcard
_label: 'What does it mean by the judgment $dash_mathcal{r} k$, where $k$ is a basic judgment and $mathcal{r}$ is a set of rules?'
deck: 'general'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-3-hypothetical-and-general-judgments.td")
---

::: flashcard
What does it mean by the judgment $\vdash_\mathcal{r} k$, where $k$ is a basic judgment and $\mathcal{r}$ is a set of rules?
=== key
:::
