---
_type: PltFlashcard
_label: 'What are the ideas of forward chaining search and backward chaining search?'
deck: 'set theory relation'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
What are the ideas of forward chaining search and backward chaining search?
=== key
Forward chaining search

Backward chaining search
:::
