---
_type: PltFlashcard
_label: 'What is operational semantics?'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/operational-semantics.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
What is operational semantics?
=== key
A style of semantics that defines a language by how it runs using syntactic transformation.
:::
