---
_type: PltFlashcard
_label: 'When a rule is not an axiom, what is it called?'
deck: 'proof technique'
concepts:
  - fref("programming-language-theory/concepts/axiom.td")
  - fref("programming-language-theory/concepts/rule.td")
  - fref("programming-language-theory/concepts/proper-rule.td")
books:
  - fref("programming-language-theory/books/software-foundations/01-logical-foundations/02-chapter-2-inductive-definitions.td")
---

::: flashcard
When a rule is not an axiom, what is it called?
=== key
Proper rule.
:::
