---
_type: Flashcard
_label: 'When is a rule satisfied by a relation?'
deck: 'logic tools'
concepts:
  - fref("programming-language-theory/concepts/inference-rule.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
When is a rule satisfied by a relation?
=== key
A rule is satisfied by a relation if for every instance of that rule, if the fact that all premises of that instance is in that relation implies that the conclusion of that instance is in that relation.
:::
