---
_type: PltFlashcard
_label: 'Where can variables be placed in an AST?'
deck: 'language theory'
concepts:
  - fref("programming-language-theory/concepts/variable.td")
books:
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/01-part-i-judgments-and-rules/01-chapter-1-abstract-syntax.td")
---

::: flashcard
Where can variables be placed in an AST?
=== key
Leaves.
:::
