---
_type: Flashcard
_label: 'Which desirable properties should hold for most systems, which would not?'
deck: 'language theory'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: flashcard
Which desirable properties should hold for most systems, which would not?
=== key
Should hold:

- Desired property: Determinacy of one-step evaluation relation.
- Desired property: Uniqueness of normal forms.
- Desired property: Value is in normal form.

Might not hold:

- Desired property: Normal form implies values.
- Desired property: Termination of evaluation.
:::
