---
_type: Flashcard
_label: 'Which notation is often used to denote a preorder relation?'
deck: 'set-theory-relation'
concepts:
  - fref("programming-language-theory/concepts/preorder.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
---

::: flashcard
Which notation is often used to denote a preorder relation?
=== key
$\le$ or $\lesssim$
:::
