---
_type: PltFlashcard
_label: 'Why does we require rules in a hypothetical inductive definition be uniform? what does it mean to be uniform?'
deck: 'general'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-3-hypothetical-and-general-judgments.td")
---

::: flashcard
Why does we require rules in a hypothetical inductive definition be uniform? what does it mean to be uniform?
=== key
:::
