---
_type: PltFlashcard
_label: 'Why is there a need for macro hygiene?'
deck: 'programming-language-basic'
concepts:
  - fref("programming-language-theory/concepts/macro.td")
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-3-syntactic-sugar.td")
---

::: flashcard
Why is there a need for macro hygiene?
=== key
To avoid Variable capture.
:::
