---
_type: PltFlashcard
_label: 'Why are type systems a valuable maintenance tool?'
deck: 'type theory'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/01-chapter-1-introduction.td")
---

::: flashcard
Why are type systems a valuable maintenance tool?
=== key
When you refactor, some function signatures or variables' types may change, a type system would catch most locations that the refactor may miss.
:::
