---
_type: PltFlashcard
_label: 'Why are most dynamically checked languages safe?'
deck: 'type theory'
concepts:
  - fref("programming-language-theory/concepts/language-safety.td")
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-1-introduction.td")
---

::: flashcard
Why are most dynamically checked languages safe?
=== key
If a runtime provides any checking at all, it's trivial to provide the utmost safety.
:::
