---
_type: Flashcard
_label: 'Why is the property that static types are checked at compile-time is valuable?'
deck: 'type theory'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
---

::: flashcard
Why is the property that static types are checked at compile-time is valuable?
=== key
- Programs may be expensive/unsafe/destructive to run.
- Runtime tests cannot cover all the state space.
:::
