---
_type: PltFlashcard
_label: 'Why is backward chaining goal-directed?'
deck: 'set theory relation'
concepts:
  - fref("programming-language-theory/concepts/backward-chaining-search.td")
  - fref("programming-language-theory/concepts/backward-chaining.td")
books:
  - fref("programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

::: flashcard
Why is backward chaining goal-directed?
=== key
Because Backward chaining starts from the goal and works backwards towards the axioms.
:::
