---
_type: Concept
title: 'Abstract binding tree abt valence abstractor'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
---

An enriched [Abstract syntax tree (AST)](/journeys/plt/concepts/abstract-syntax-tree-ast) with bindings and scopes. According to Practical foundations for programming languages , each node in an ABT is either a Variable or an Operator whose arguments are Abstractors.
