---
_type: Concept
title: 'Algebraic data type'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'language-feature-design'
  - 'programming-paradigm'
  - 'type-theory'
---

A composite type formed by combining ${fref("journeys/programming-language-theory/concepts/sum-type.td")}s (variants/tagged unions) and product types (tuples/records), enabling precise modeling of data structures like Option, Result, or tree nodes. Synonymous with [Sum of products (SoP)](/journeys/plt/concepts/sum-of-products-sop).
