---
_type: Concept
title: 'AST rewriting'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-3-syntactic-sugar.td")
tags:
  - 'compiler-implementation'
  - 'language-feature-design'
  - 'metaprogramming-self-reflection'
  - 'syntax-grammar'
---

A program transformation technique that modifies the ${fref("journeys/programming-language-theory/concepts/abstract-syntax-tree-ast.td")} to implement features like ${fref("journeys/programming-language-theory/concepts/macro.td")}s, optimizations, or language extensions before code generation.
