---
_type: Concept
title: 'Axiom'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
tags:
  - 'logic'
---

A ${fref("journeys/programming-language-theory/concepts/rule.td")} with no ${fref("journeys/programming-language-theory/concepts/premise.td")}.
