---
_type: Concept
title: 'Backward chaining'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
tags:
  - 'logic'
  - 'proof-reason-technique'
  - 'set-theory-relation'
---

A proof technique for ${fref("journeys/programming-language-theory/concepts/judgment.td")}s that starts from the desired judgement and works backwards towards the ${fref("journeys/programming-language-theory/concepts/axiom.td")}s.
