---
_type: Concept
title: 'Behavioral/Observational/Contextual equivalence'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
tags:
  - 'program-analysis'
  - 'semantics'
---

Example: $\lambda x.\ x \simeq \lambda x.\ (\lambda y.\ y)\ x$
