---
_type: Concept
title: 'Beta-redex/Reducible expression'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

A term of the form: $t_1\ t_2$, in which $t_1$ is a ${fref("journeys/programming-language-theory/concepts/lambda-abstraction.td")} and $t_2$ is any term.
