---
_type: Concept
title: 'Binding structure of syntax'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
tags:
  - 'compiler-implementation'
  - 'semantics'
  - 'syntax-grammar'
---

A generalization of [Abstract binding tree (ABT)](/journeys/plt/concepts/abstract-binding-tree-abt).
