---
_type: Concept
title: 'Block'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

A syntactic construct that groups statements and typically introduces a new scope for local bindings - delimited by braces { }, keywords (begin/end), or indentation depending on the language.

A syntactic construct that groups statements and typically introduces a new scope for local bindings - delimited by braces `{ }`, keywords (`begin`/`end`), or indentation depending on the language.
