---
_type: Concept
title: 'BNF'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

A ${fref("journeys/programming-language-theory/concepts/metalanguage.td")} notation for specifying ${fref("journeys/programming-language-theory/concepts/context-free.td")} grammars, using production rules of the form $\text{<nonterminal>} ::= \text{expression}$ to define the syntax of formal languages.
