---
_type: Concept
title: 'Calculus of inductive construction'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
tags:
  - 'computation-theory'
  - 'formal-system'
  - 'logic'
---

Tools: Rocq (formerly Coq)

- (Formal system, Logic, Computation theory) A **type theory** combining ${fref("journeys/programming-language-theory/concepts/dependent-type.td")}s, ${fref("journeys/programming-language-theory/concepts/inductive-type.td")}s, and a hierarchy of universes, serving as the theoretical foundation of ${fref("journeys/programming-language-theory/concepts/coq.td")}.
