---
_type: Concept
title: 'Closure'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

::: info
(Language feature/design, Semantics) A function value that remembers its surrounding ${fref("journeys/programming-language-theory/concepts/environment.td")}.
:::
