---
_type: Concept
title: 'Combinator'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
---

A ${fref("journeys/programming-language-theory/concepts/lambda-term.td")} that contains no ${fref("journeys/programming-language-theory/concepts/free-variable.td")}, or in other words, a ${fref("journeys/programming-language-theory/concepts/closed-term.td")}.
