---
_type: Concept
title: 'Complete'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
tags:
  - 'formal-system'
  - 'logic'
  - 'set-theory-relation'
---

The adjective form of ${fref("journeys/programming-language-theory/concepts/completeness.td")}.
