---
_type: Concept
title: 'Conclusion'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
tags:
  - 'logic'
---

The consequent ${fref("journeys/programming-language-theory/concepts/judgment.td")} of an ${fref("journeys/programming-language-theory/concepts/inference-rule.td")} that is derived when all its ${fref("journeys/programming-language-theory/concepts/premise.td")}s are satisfied.
