---
_type: Concept
title: 'Conditional expression'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
---

An expression that selects between alternatives based on a boolean or ${fref("journeys/programming-language-theory/concepts/pattern-matching.td")} (like if b then x else y or ternary b ? x : y).

An **expression** that selects between alternatives based on a boolean or pattern match (like `if b then x else y` or ternary `b ? x : y`).
