---
_type: Concept
title: 'Congruence'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
---

An ${fref("journeys/programming-language-theory/concepts/equivalence.td")} relation that is preserved under a specific operation. That is, assume a congruence $\mathcal{C}$ and an operation $p$, we have $a\ \mathcal{C}\ b \iff p(a)\ \mathcal{C}\ p(b)$.
