---
_type: Concept
title: 'Constructor expression constructor'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
---

[Rocq] An **expression** that applies a [constructor](/journeys/programming-language-theory/concepts/constructor) to arguments to build a value of an [inductive type](/journeys/programming-language-theory/concepts/inductive-type) (like `S (S O)` for 2, or `Some 42` for an optional integer).
