---
_type: Concept
title: 'Currying'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
tags:
  - 'language-feature-design'
---

The act of turning a multi-parameter function into a ${fref("journeys/programming-language-theory/concepts/higher-order-function.td")}  that accepts one argument and returns a partially-applied version of the original function.
