---
_type: Concept
title: 'Denotational semantics'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

A style of semantics that gives meanings to terms compositionally by mapping them to mathematical objects that possess interesting behaviors.
