---
_type: Concept
title: 'Derivation'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
tags:
  - 'logic'
  - 'set-theory-relation'
---

A finite composition of rules, starting with ${fref("journeys/programming-language-theory/concepts/axiom.td")}s and ending with a desired ${fref("journeys/programming-language-theory/concepts/judgment.td")}.
