---
_type: Concept
title: "Desired property: uniqueness of normal forms"
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
tags:
  - 'lambda-calculus'
  - 'semantics'
---

A desirable property of a ${fref("journeys/programming-language-theory/concepts/lambda-calculus.td")} where every term always evaluates to the same ${fref("journeys/programming-language-theory/concepts/normal-form.td")}. This property should hold in all deterministic systems.
