---
_type: Concept
title: "Desired property: normal form implies values"
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
tags:
  - 'lambda-calculus'
  - 'semantics'
---

A desirable property of a ${fref("journeys/programming-language-theory/concepts/lambda-calculus.td")} where there's no ${fref("journeys/programming-language-theory/concepts/stuck-term.td")}. This property may not hold in most systems.
