---
_type: Concept
title: 'Desugar'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-3-syntactic-sugar.td")
tags:
  - 'compiler-implementation'
  - 'language-feature-design'
  - 'metaprogramming-self-reflection'
  - 'syntax-grammar'
---

The process of transforming ${fref("journeys/programming-language-theory/concepts/syntactic-sugar.td")} or high-level constructs into more primitive forms in the ${fref("journeys/programming-language-theory/concepts/core-calculus-language.td")}, simplifying the interpreter or compiler implementation.
