---
_type: Concept
title: 'Directed acyclic graph (DAG)'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
tags:
  - 'data-structure-algorithm'
---

- Edges have a direction (from one node to another).
- There are no cycles (you can't follow edges and return to where you started).
