---
_type: Concept
title: 'Divergent term'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
tags:
  - 'lambda-calculus'
  - 'semantics'
---

A term that does not evaluate to a ${fref("journeys/programming-language-theory/concepts/normal-form.td")}.
