---
_type: Concept
title: 'Duck typing'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'language-feature-design'
  - 'programming-paradigm'
  - 'semantics'
  - 'type-theory'
---

An informal term for Structural typing - if an object has the required methods/properties (\"quacks like a duck\"), it can be used regardless of its declared type or class hierarchy.

An informal term for ${fref("journeys/programming-language-theory/concepts/structural-typing.td")} - if an object has the required methods/properties ("quacks like a duck"), it can be used regardless of its declared type or class hierarchy.
