---
_type: Concept
title: 'Expression'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
tags:
  - 'lambda-calculus'
  - 'language-feature-design'
  - 'semantics'
  - 'syntax-grammar'
---

::: info
(Semantics, Syntax & Grammar, Language feature/design) A syntactic construct that evaluates to a value, as opposed to a ${fref("journeys/programming-language-theory/concepts/statement.td")}.
:::
