---
_type: Concept
title: 'Extensible/Open recursion'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
tags:
  - 'design-principle'
  - 'language-feature-design'
  - 'programming-paradigm'
---

When utilizing the ${fref("journeys/programming-language-theory/concepts/class-pattern.td")} to define classes with method calls referencing other methods, a recursion pattern that allows method references to be resolved at call site.
