---
_type: Concept
title: 'First-class'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
tags:
  - 'language-feature-design'
  - 'semantics'
  - 'syntax-grammar'
---

- Can be stored in variables.
- Passed as arguments.
- Returned from functions.
- Created at runtime.
- Embedded in data structures without restriction.
