---
_type: Concept
title: 'Flow analysis'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'language-feature-design'
  - 'program-analysis'
  - 'runtime'
  - 'semantics'
  - 'type-theory'
---

A static analysis technique that tracks how information propagates through a program's control flow - determining what facts hold at each program point based on paths taken.

A ${fref("journeys/programming-language-theory/concepts/static-analysis.td")} technique that tracks how **information propagates** through a program's control flow - determining what facts hold at each program point based on paths taken.
