---
_type: Concept
title: 'Formal parameter'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
tags:
  - 'language-feature-design'
  - 'syntax-grammar'
---

The variable declared in a function definition that receive values when called - placeholders in the function signature.
