---
_type: Concept
title: 'Free variable'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
tags:
  - 'lambda-calculus'
  - 'syntax-grammar'
---

A variable that is not bound by any enclosing $\lambda$. Contrast with ${fref("journeys/programming-language-theory/concepts/bound-variable.td")}.
