---
_type: Concept
title: 'Function'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
tags:
  - 'language-feature-design'
  - 'set-theory-relation'
---

::: info
(Language feature/design) A reusable piece of code that returns a result.
:::
