---
_type: Concept
title: 'Function header'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
tags:
  - 'language-feature-design'
  - 'syntax-grammar'
---

The declarative part of a function that specifies its name, ${fref("journeys/programming-language-theory/concepts/formal-parameter.td")}s, and return type (if any), without the body implementation.
