---
_type: Concept
title: 'Goal'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
tags:
  - 'formal-system'
  - 'language-feature-design'
  - 'logic'
  - 'programming-paradigm'
  - 'proof-reason-technique'
---

Tools: Rocq (formerly Coq)

- (Formal system, Proof/Reason technique, Language feature/design, Programming paradigm) In ${fref("journeys/programming-language-theory/concepts/rocq.td")}, the ${fref("journeys/programming-language-theory/concepts/proposition.td")} **to be proven** at any point during a proof, which ${fref("journeys/programming-language-theory/concepts/tactic.td")}s transform until it becomes trivially true.
- (Formal system, Proof/Reason technique, Logic) A ${fref("journeys/programming-language-theory/concepts/proposition.td")} to be proven.
