---
_type: Concept
title: 'Heap address'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
tags:
  - 'runtime'
---

An address on the ${fref("journeys/programming-language-theory/concepts/heap.td")}.
