---
_type: Concept
title: 'Hoare type theory'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/software-foundations/logical-foundations.td")
tags:
  - 'formal-system'
  - 'logic'
  - 'program-analysis'
  - 'proof-reason-technique'
  - 'semantics'
---

A type theory that integrates Hoare-style specifications into types, allowing pre/postconditions and invariants to be expressed and checked within a dependently typed language.

A ${fref("journeys/programming-language-theory/concepts/type-theory.td")} that integrates ${fref("journeys/programming-language-theory/concepts/hoare-logic.td")}-style specifications into types, allowing pre/postconditions and invariants to be expressed and checked within a dependently typed language.
