---
_type: Concept
title: 'Immediately invoked function expression (IIFE)'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-3-syntactic-sugar.td")
tags:
  - 'language-feature-design'
  - 'programming-paradigm'
  - 'syntax-grammar'
---

Example: ${fref("journeys/programming-language-theory/concepts/parallel-simultaneous-let.td")} in Scheme is actually a ${fref("journeys/programming-language-theory/concepts/syntactic-sugar.td")} for IIFE.
