---
_type: Concept
title: 'Inductive type'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
tags:
  - 'language-feature-design'
  - 'type-theory'
---

Tools: Rocq (formerly Coq)

::: info
(Type theory, Formal system) A **type** defined by a finite set of ${fref("journeys/programming-language-theory/concepts/constructor.td")}s that specify all possible ways to build its values, enabling ${fref("journeys/programming-language-theory/concepts/pattern-matching.td")} and ${fref("journeys/programming-language-theory/concepts/structural-recursion.td")} (like `nat`, `list`, or `tree`).
:::
