---
_type: Concept
title: 'Induction on derivations'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

An induction technique in which to prove a specific property about a ${fref("journeys/programming-language-theory/concepts/derivation.td")}, we take the ${fref("journeys/programming-language-theory/concepts/inductive-hypothesis.td")} is that every smaller derivations satisfy that property.
