---
_type: Concept
title: 'Inference rule'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

::: info
(Logic) A formal statement consisting of ${fref("journeys/programming-language-theory/concepts/premise.td")}s and a ${fref("journeys/programming-language-theory/concepts/conclusion.td")}, asserting that if all premises hold, the conclusion may be derived.
:::
