---
_type: Concept
title: 'Inheritance'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
tags:
  - 'language-feature-design'
  - 'programming-paradigm'
---

A mechanism where a class (subclass) derives properties and behaviors from another class (superclass), enabling code reuse and establishing an \"is-a\" relationship between types. This coupling between

A mechanism where a class (${fref("journeys/programming-language-theory/concepts/subclass.td")}) derives properties and behaviors from another class (${fref("journeys/programming-language-theory/concepts/supertype.td")}), enabling code reuse and establishing an "is-a" relationship between types. This coupling between code reuse and ${fref("journeys/programming-language-theory/concepts/subtyping.td")} is one of the core issues of inheritance.
