---
_type: Concept
title: 'Instance of the judgment form'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
tags:
  - 'logic'
  - 'set-theory-relation'
---

A ${fref("journeys/programming-language-theory/concepts/judgment-form.td")} applied with one or more values. For a judgment form $-\ J$ and a value $a$, it is written as $a\ J$ or $J\ a$.
