---
_type: Concept
title: 'Interpretation'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
tags:
  - 'semantics'
---

A semantic mapping that assigns meaning to a Representation (e.g., 0b101 can interpret as 5 in binary or a bit pattern).

A **semantic mapping** that assigns meaning to a ${fref("journeys/programming-language-theory/concepts/representation.td")} (e.g., `0b101` can interpret as `5` in binary or a bit pattern).
