---
_type: Concept
title: 'Interpreter'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
tags:
  - 'compiler-implementation'
  - 'runtime'
---

Mathematically, denote $\mathcal{P}_L$ as the set of programs written in the language $L$ and $V$ the set of all possible values, an interpreter is a function $I: \mathcal{P}_L \to V$.
