---
_type: Concept
title: 'Judgment judgment form'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
---

Synonymous with an n-place relation. For a unary relation/${fref("journeys/programming-language-theory/concepts/predicate.td")}, a ${fref("journeys/programming-language-theory/concepts/judgment-form.td")} is usually written as $J\ -$ or $-\ J$, with $-$ being a placeholder for some value drawn from the domain of the predicate.
