---
_type: Concept
title: 'Just-in-time (JIT) compilation'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
---

An ${fref("journeys/programming-language-theory/concepts/evaluator.td")} that starts out as an ${fref("journeys/programming-language-theory/concepts/interpreter.td")} but includes a monitor to detect, compile and utilize compiled hot code.
