---
_type: Concept
title: 'Labeled tree'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
tags:
  - 'compiler-implementation'
  - 'syntax-grammar'
---

Synonymous with [Abstract syntax tree (AST)](/journeys/plt/concepts/abstract-syntax-tree-ast).
