---
_type: Concept
title: 'Lexical analysis parsing'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
---

A step in the ${fref("journeys/programming-language-theory/concepts/compiler.td")} that involves converting texts into sequences of ${fref("journeys/programming-language-theory/concepts/token.td")}s. This typically involves:

- Removing comments and whitespaces.
- Categorizing tokens.

The process of classifying texts into syntactic categories.
