---
_type: Concept
title: 'Lexical analysis'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
tags:
  - 'compiler-implementation'
  - 'linguistics'
  - 'syntax-grammar'
---

::: info
(Syntax & Grammar, Linguistics) The process of classifying texts into ${fref("journeys/programming-language-theory/concepts/syntactic-category.td")}s.
:::

- Removing comments and whitespaces.
- Categorizing tokens.
