---
_type: Concept
title: 'Literal'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
tags:
  - 'language-feature-design'
  - 'syntax-grammar'
---

Synonymous with syntactic ${fref("journeys/programming-language-theory/concepts/constant.td")}.
