---
_type: Concept
title: 'Logic'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/software-foundations/logical-foundations.td")
tags:
  - 'formal-system'
  - 'logic'
---

A ${fref("journeys/programming-language-theory/concepts/formal-system.td")} for reasoning about truth, validity, and inference, defining syntax for propositions and rules for deriving conclusions.

A **formal system** for reasoning about truth, validity, and inference, defining syntax for propositions and rules for deriving conclusions.
