---
_type: Concept
title: 'Meet'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
tags:
  - 'order-lattice-theory'
---

In the context of a ${fref("journeys/programming-language-theory/concepts/partial-order.td")}, the greatest lower bound of a set $S$, denoted as $\bigwedge S$ .
