---
_type: Concept
title: 'Message passing'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
tags:
  - 'concurrency-theory'
  - 'design-principle'
  - 'programming-paradigm'
---

```scheme
(define msg (obj name . args)
	((obj name) args))
```
