---
_type: Concept
title: 'Metatheory'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

The study of properties about a ${fref("journeys/programming-language-theory/concepts/formal-system.td")} (e.g., ${fref("journeys/programming-language-theory/concepts/sound.td")}ness, ${fref("journeys/programming-language-theory/concepts/completeness.td")}, termination), using external reasoning to prove facts about the system itself.
