---
_type: Concept
title: 'Metavariable'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

A variable in the ${fref("journeys/programming-language-theory/concepts/metalanguage.td")} that ranges over elements of a ${fref("journeys/programming-language-theory/concepts/syntactic-category.td")} in the object language - e.g., $t$ ranging over terms, $v$ over values, $x$ over variables.
