---
_type: Concept
title: 'Multiple inheritance'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
tags:
  - 'language-feature-design'
  - 'programming-paradigm'
  - 'semantics'
---

An ${fref("journeys/programming-language-theory/concepts/inheritance.td")} model where a class can inherit from multiple parent classes, combining their behaviors but potentially introducing ambiguity (${fref("journeys/programming-language-theory/concepts/the-diamond-problem.td")}) when parents share method names.
