---
_type: Concept
title: 'Object member'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
tags:
  - 'language-feature-design'
  - 'programming-paradigm'
---

A component of an object, either a ${fref("journeys/programming-language-theory/concepts/field.td")} (data) or a ${fref("journeys/programming-language-theory/concepts/method.td")} (behavior).
