---
_type: Concept
title: 'Object'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
---

A multi-entrypoint ${fref("journeys/programming-language-theory/concepts/closure.td")} that can be accessed using ${fref("journeys/programming-language-theory/concepts/message-passing.td")}.
