---
_type: Concept
title: 'Operational semantics untyped calculus of booleans and'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
---

A style of semantics that defines the meaning of programs by syntactically transforming terms according to reduction rules, specifying execution either step-by-step ([Small-step/Structural operational semantics (SOS)](Small-step%20Structural%20operational%20semantics%20(SOS)%202c7aa8fcd08880f1b83aecba03d1192e.md)) or as a direct relation to final values (Big-step/Natural operational semantics).
