---
_type: Concept
title: 'Operator'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
tags:
  - 'syntax-grammar'
---

According to Practical foundations for programming languages , an interior node of an [Abstract syntax tree (AST)](/journeys/plt/concepts/abstract-syntax-tree-ast), with a specified Arity $(s_1;\dots; s_n)s$, for $s_i \in \mathcal{S}$ - the set of Sorts.
