---
_type: Concept
title: 'Partial function'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
tags:
  - 'set-theory-relation'
---

A ${fref("journeys/programming-language-theory/concepts/binary-relation.td")} $R$ such that if $s\ R\ t_1$ and $s\ R\ t_2$ then $t_1 = t_2$.
