---
_type: Concept
title: 'Partiality'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'computation-theory'
  - 'semantics'
  - 'set-theory-relation'
---

The property of a computation that may not terminate or produce a result for all inputs. ${fref("journeys/programming-language-theory/concepts/partial-function.td")}s are undefined for some inputs, unlike ${fref("journeys/programming-language-theory/concepts/total-function.td")}s which always return a value.
