---
_type: Concept
title: 'Predicate'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
tags:
  - 'set-theory-relation'
---

An unary n-place relation $P$, $(s) \in P$  is typically written as $P(s)$.
