---
_type: Concept
title: 'Premise'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
tags:
  - 'logic'
---

An antecedent judgment in an ${fref("journeys/programming-language-theory/concepts/inference-rule.td")} that must be ${fref("journeys/programming-language-theory/concepts/derivable.td")} for the rule to derive its ${fref("journeys/programming-language-theory/concepts/conclusion.td")}.
