---
_type: Concept
title: 'Preorder'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
---

A ${fref("journeys/programming-language-theory/concepts/binary-relation.td")} that is ${fref("journeys/programming-language-theory/concepts/reflexive.td")} and ${fref("journeys/programming-language-theory/concepts/transitive.td")}.
