---
_type: Concept
title: 'Procedural/Functional abstraction'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
tags:
  - 'language-feature-design'
  - 'semantics'
  - 'syntax-grammar'
---

The principle of encapsulating a computation behind a named interface, hiding implementation details and allowing reuse by parameterizing over inputs.
