---
_type: Concept
title: 'Proper rule'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
tags:
  - 'logic'
  - 'set-theory-relation'
---

An ${fref("journeys/programming-language-theory/concepts/inference-rule.td")} that is not an ${fref("journeys/programming-language-theory/concepts/axiom.td")}, in other words, has at least one ${fref("journeys/programming-language-theory/concepts/premise.td")}s.
