---
_type: Concept
title: 'Pure'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
  - fref("journeys/programming-language-theory/books/software-foundations/logical-foundations.td")
tags:
  - 'design-principle'
  - 'program-analysis'
  - 'programming-paradigm'
  - 'semantics'
---

The property of a function or computation that has no side effects and always returns the same output for the same input, making it referentially transparent.
