---
_type: Concept
title: 'Rocq constructor function computation rule'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
---

A ${fref("journeys/programming-language-theory/concepts/constructor-expression.td")} is an expression constructed using a ${fref("journeys/programming-language-theory/concepts/constructor.td")}, effectively creating a member of a set represented by a type.
