---
_type: Concept
title: 'Rule schema'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
tags:
  - 'logic'
---

An parameterized inference rules with ${fref("journeys/programming-language-theory/concepts/metavariable.td")}s that can be instantiated to ${fref("journeys/programming-language-theory/concepts/concrete-rule.td")}s or ${fref("journeys/programming-language-theory/concepts/inference-rule.td")}s.
