---
_type: Concept
title: 'Rule schema inference rule concrete rule instance of an'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
---

An parameterized inference rules with ${fref("journeys/programming-language-theory/concepts/metavariable.td")}s that can be instantiated to ${fref("journeys/programming-language-theory/concepts/concrete-rule.td")}s or ${fref("journeys/programming-language-theory/concepts/inference-rule.td")}s.
