---
_type: Concept
title: 'Set comprehension'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
tags:
  - 'set-theory-relation'
---

Example: $\mathbb{Q} = \{\displaystyle \frac{p}{q}\ |\ p \in \mathbb{Z} \land q \in \mathbb{Z} \land q \neq 0 \}$.
