---
_type: Concept
title: 'Shadowing'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
tags:
  - 'language-feature-design'
  - 'semantics'
---

The phenomenon when an inner ${fref("journeys/programming-language-theory/concepts/binding.td")} uses the same name as an outer binding, making the outer one inaccessible within the inner ${fref("journeys/programming-language-theory/concepts/scope.td")}.
