---
_type: Concept
title: 'Simultaneous inductive definition'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
---

A definition technique that define more than one sets at once as a collection of ${fref("journeys/programming-language-theory/concepts/inference-rule.td")}s to determine membership of the elements of the sets - each inference rule shall refer to the sets in its ${fref("journeys/programming-language-theory/concepts/premise.td")}s and its ${fref("journeys/programming-language-theory/concepts/conclusion.td")}s.
