---
_type: Concept
title: 'Small omega combinator'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
tags:
  - 'lambda-calculus'
  - 'syntax-grammar'
---

A ${fref("journeys/programming-language-theory/concepts/combinator.td")} defined as $\omega = \lambda x.\ x\ x$, useful in many patterns, such as ${fref("journeys/programming-language-theory/concepts/extensible-open-recursion.td")}.
