---
_type: Concept
title: 'Sort'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
---

A Syntactic category that classifies [Abstract syntax tree (AST)](/journeys/plt/concepts/abstract-syntax-tree-ast)s. Roughly a type for ASTs.
