---
_type: Concept
title: 'Static discipline'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'program-analysis'
  - 'syntax-grammar'
  - 'type-theory'
---

An approach where ${fref("journeys/programming-language-theory/concepts/static-analysis.td")} and other analyses are performed before program execution, catching errors at compile time rather than runtime. Contrasts with dynamic discipline.
