---
_type: Concept
title: 'Statement'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
tags:
  - 'language-feature-design'
  - 'semantics'
  - 'syntax-grammar'
---

A ${fref("journeys/programming-language-theory/concepts/term.td")} that does not evaluate to a value, but rather cause a ${fref("journeys/programming-language-theory/concepts/side-effect.td")}.
