---
_type: Concept
title: 'Substitutability'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'language-feature-design'
  - 'semantics'
  - 'type-theory'
---

The semantic/behavioral property that one value can safely replace another without breaking program correctness, of which ${fref("journeys/programming-language-theory/concepts/type-compatibility.td")} is a static approximation of.

The semantic/behavioral property that one value can **safely replace** another without breaking program correctness, of which ${fref("journeys/programming-language-theory/concepts/type-compatibility.td")} is a static approximation of.
