---
_type: Concept
title: 'Top-down construction'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
tags:
  - 'logic'
  - 'proof-reason-technique'
  - 'set-theory-relation'
---

Synonymous with ${fref("journeys/programming-language-theory/concepts/backward-chaining.td")}.
