---
_type: Concept
title: 'Total function'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
tags:
  - 'set-theory-relation'
---

A ${fref("journeys/programming-language-theory/concepts/partial-function.td")} that is defined on all values of its domain.
