---
_type: Concept
title: 'Type checker'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'compiler-implementation'
  - 'type-theory'
---

A program or algorithm that verifies type correctness by analyzing program text and ensuring expressions conform to typing rules before execution.
