---
_type: Concept
title: 'Type annotation'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-1-introduction.td")
tags:
  - 'syntax-grammar'
  - 'type-theory'
---

A syntactic hint to the ${fref("journeys/programming-language-theory/concepts/type-checker.td")} declaring the intended type of a term, used to guide inference, resolve ambiguity, or make types explicit for documentation.
