---
_type: Concept
title: 'Type compatibility'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'language-feature-design'
  - 'semantics'
  - 'set-theory-relation'
  - 'type-theory'
---

A relation between types that implies ${fref("journeys/programming-language-theory/concepts/substitutability.td")}. A static approximation of Substitutability.
