---
_type: Concept
title: 'Type widening'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
tags:
  - 'language-feature-design'
  - 'semantics'
  - 'type-theory'
---

Analogy: Think of types as sets, then type widening means to widen a set (${fref("journeys/programming-language-theory/concepts/subtype.td")} -> ${fref("journeys/programming-language-theory/concepts/supertype.td")}).
