---
_type: Concept
title: 'Type narrowing'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
tags:
  - 'language-feature-design'
  - 'semantics'
  - 'type-theory'
---

Analogy: Think of types as sets, then type narrowing means to narrow a set (${fref("journeys/programming-language-theory/concepts/supertype.td")} -> ${fref("journeys/programming-language-theory/concepts/subtype.td")}).
