---
_type: Concept
title: 'Type inference'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
---

The automatic deduction of types from program context without explicit annotations, using constraint solving or unification algorithms (e.g., ${fref("journeys/programming-language-theory/concepts/hindley-milner-system.td")}) to determine (usually) the most general types.
