---
_type: Concept
title: 'Type constructor'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'language-feature-design'
  - 'type-theory'
---

A function at the type level that builds new types from existing ones, such as List, Array, or the arrow constructor ($\\to$) that constructs function types.

A function at the type level that builds new types from existing ones, such as `List`, `Array`, or the arrow constructor ($\to$) that constructs function types.
