---
_type: Concept
title: 'Type safety'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/practical-foundations-for-programming-languages/preface.td")
tags:
  - 'language-feature-design'
  - 'semantics'
  - 'type-theory'
---

::: info
(Type theory, Language feature/design, Semantics) According to Robert (Bob) Harper, the coherence between ${fref("journeys/programming-language-theory/concepts/static-semantics.td")} and ${fref("journeys/programming-language-theory/concepts/dynamic-semantics.td")}.
:::
