---
_type: Concept
title: 'Type variant'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'language-feature-design'
  - 'type-theory'
---

A variant of a ${fref("journeys/programming-language-theory/concepts/sum-type.td")}.
