---
_type: Concept
title: 'Valence'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
tags:
  - 'syntax-grammar'
---

The specification of how many variables a subterm binds and what ${fref("journeys/programming-language-theory/concepts/sort.td")}s (types) those variables have.
