---
_type: Concept
title: 'Value'
journey: fref("journeys/programming-language-theory/index.td")
status: 'learning'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

A ${fref("journeys/programming-language-theory/concepts/term.td")} in ${fref("journeys/programming-language-theory/concepts/normal-form.td")} that is not deemed a bad state.
