---
_type: Concept
title: 'Vector'
journey: fref("journeys/programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("journeys/programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
tags:
  - 'data-structure-algorithm'
---

A contiguous, dynamically-sized array data structure supporting indexed access and operations like append, typically allocated on the ${fref("journeys/programming-language-theory/concepts/heap.td")}.
