---
_type: Concept
title: 'Well-founded'
journey: fref("journeys/programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("journeys/programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
tags:
  - 'order-lattice-theory'
---

The property of a ${fref("journeys/programming-language-theory/concepts/preorder.td")} whose strict part ($a < b \iff a \le b\land b \not\le a$ ) admits no infinite descending chains, ensuring every non-empty subset has a minimal element.
