---
_type: Concept
title: '2-dimensional inference rule format'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
tags:
  - 'logic'
  - 'set-theory-relation'
  - 'syntax-grammar'
---

A style of formal definition that defines a set inductively as the smallest set closed under the rules - an element is in the set iff it can be derived by a finite ${fref("programming-language-theory/concepts/derivation-tree.td")} of rule applications.

${fref("concepts/plt/assets/2d-inference-rule.png")}
