---
_type: Concept
title: 'Abstract machine'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
tags:
  - 'compiler-implementation'
  - 'computation-theory'
  - 'linguistics'
  - 'runtime'
---

A formal model of computation defined by a set of states, an initial state, final states, and a ${fref("programming-language-theory/concepts/transition-function.td")} specifying how states evolve step-by-step until halting.
