---
_type: Concept
title: 'Abstract binding graph'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
---

An extension of [Abstract binding tree (ABT)](/plt/concepts/abstract-binding-tree-abt)s to a [Directed acyclic graph (DAG)](/plt/concepts/directed-acyclic-graph-dag) structure while preserving the binding discipline.
