---
_type: Concept
_label: 'Actual parameter/argument'
title: 'Actual parameter/argument'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
tags:
  - 'language-feature-design'
  - 'semantics'
  - 'syntax-grammar'
---

::: info
(Syntax & Grammar) According to Practical foundations for programming languages , the child of an Operator in an [Abstract syntax tree (AST)](/plt/concepts/abstract-syntax-tree-ast).
:::
