---
_type: Concept
_label: 'Alpha-variant'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
tags:
  - 'semantics'
  - 'syntax-grammar'
---

If two terms are related by the ${fref("programming-language-theory/concepts/alpha-equivalence.td")} relation, they are alpha-variants.
