---
_type: Concept
_label: 'Automatic memory management'
title: 'Automatic memory management'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

A language or runtime mechanism that handles allocation and deallocation of memory without explicit programmer intervention - encompassing techniques like ${fref("programming-language-theory/concepts/garbage-collection.td")}, reference counting, and ownership systems.
