---
_type: Concept
_label: 'Beta-reduction'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
tags:
  - 'lambda-calculus'
  - 'semantics'
---

The act of reducing a ${fref("programming-language-theory/concepts/beta-redex-reducible-expression.td")} by substituting the redex's argument into its function body.
