---
_type: Concept
_label: 'Beta-equivalence'
title: 'Beta-equivalence'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
tags:
  - 'lambda-calculus'
  - 'semantics'
---

A ${fref("programming-language-theory/concepts/binary-relation.td")} that relates terms connected by ${fref("programming-language-theory/concepts/beta-reduction.td")}  - $(\lambda x.\ t)\ s =_\beta [x\to s]t$ - capturing the fundamental computation rule of function application.
