---
_type: Concept
_label: 'Big-step/Natural operational semantics'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
tags:
  - 'formal-system'
  - 'semantics'
---

A style of semantic which defines evaluation via ${fref("programming-language-theory/concepts/evaluation-statement-judgement.td")} of the form $t \\Downarrow v$, relating a term directly to its final value in a single derivation rather than through int

A style of semantic which defines evaluation via Evaluation statement/judgement of the form $t \Downarrow v$, relating a term directly to its final value in a single derivation rather than through intermediate steps.
