---
_type: Concept
title: 'Binder'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
tags:
  - 'lambda-calculus'
  - 'syntax-grammar'
---

A syntactic construct that introduces a variable and defines its scope. In ${fref("programming-language-theory/concepts/lambda-calculus.td")}, it's the variable directly following $\lambda$.
