---
_type: Concept
_label: 'Call by need call by name call by value normal order full'
title: 'Call by need call by name call by value normal order full'
journey: fref("programming-language-theory/index.td")
status: 'learning'
---

::: info
(Lambda calculus, Semantics, Pure lambda calculus) An evaluation strategy similar to ${fref("programming-language-theory/concepts/call-by-name.td")}, but terms' values are cached to avoid re-evaluation.
:::
