---
_type: Concept
_label: 'Call by need'
title: 'Call by need'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
tags:
  - 'language-feature-design'
  - 'semantics'
---

::: info
(Lambda calculus, Semantics, Pure lambda calculus) An evaluation strategy similar to ${fref("programming-language-theory/concepts/call-by-name.td")}, but terms' values are cached to avoid re-evaluation.
:::
