---
_type: Concept
title: 'Constructor expression'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
tags:
  - 'language-feature-design'
---

[Rocq] An **expression** that applies a [constructor](/programming-language-theory/concepts/constructor) to arguments to build a value of an [inductive type](/programming-language-theory/concepts/inductive-type) (like `S (S O)` for 2, or `Some 42` for an optional integer).
