---
_type: Concept
_label: 'Consequent'
title: 'Consequent'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'logic'
---

The part below the line in a typing rule - the ${fref("programming-language-theory/concepts/conclusion.td")} that follows when all ${fref("programming-language-theory/concepts/antecedent.td")}s are satisfied (\"then\" part).

The part **below** the line in a typing rule - the Conclusion that follows when all Antecedents are satisfied ("then" part).
