---
_type: Concept
_label: 'Context-free'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'computation-theory'
  - 'linguistics'
  - 'syntax-grammar'
---

A grammar where production rules depend only on a single non-terminal, not its surroundings - parsers handle this level; e.g., balanced parentheses, syntax structure.

A grammar where production rules depend only on a **single non-terminal**, not its surroundings - parsers handle this level; e.g., balanced parentheses, syntax structure.
