---
_type: Concept
title: 'Decidability'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'computation-theory'
  - 'logic'
---

A property of a problem or language where an algorithm exists that can always determine the correct yes/no answer in finite time for any input.
