---
_type: Concept
title: 'Elimination rule'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'logic'
---

Example:

$$
\frac{A \land B}{A} \land E_1
$$
