---
_type: Concept
title: 'Equivalence'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
---

A ${fref("programming-language-theory/concepts/reflexive.td")}, ${fref("programming-language-theory/concepts/transitive.td")} and ${fref("programming-language-theory/concepts/symmetric.td")} relation.
