---
_type: Concept
title: 'First-order variable'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
---

A variable that ranges over data values (e.g., integers, booleans, records) - as opposed to ${fref("programming-language-theory/concepts/higher-order-function.td")} variables which can hold functions or other computational entities.
