---
_type: Concept
_label: 'Forward chaining forward chaining search'
title: 'Forward chaining forward chaining search'
journey: fref("programming-language-theory/index.td")
status: 'learning'
---

A proof technique for ${fref("programming-language-theory/concepts/judgment-form.td")}s that starts with an ${fref("programming-language-theory/concepts/axiom.td")} and tries to derive the desired judgment.
