---
_type: Concept
_label: 'Forward chaining search backward chaining search'
title: 'Forward chaining search backward chaining search'
journey: fref("programming-language-theory/index.td")
status: 'learning'
---

A search strategy for a ${fref("programming-language-theory/concepts/derivation.td")} of a ${fref("programming-language-theory/concepts/judgment-form.td")} that keeps track of the currently derivable judgments (initially the ${fref("programming-language-theory/concepts/axiom.td")}s) and tries to expand the set using the rules at each step.
