---
_type: Concept
_label: 'Gallina'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
tags:
  - 'formal-system'
  - 'language-feature-design'
  - 'proof-reason-technique'
---

A ${fref("programming-language-theory/concepts/functional-programming.td")} language (${fref("programming-language-theory/concepts/rocq.td")}'s specification language) that allows writing purely functional programs and formal proofs, using ${fref("programming-language-theory/concepts/dependent-type.td")} to express precise logical properties.
