---
_type: Concept
title: 'Goal-directed'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
tags:
  - 'data-structure-algorithm'
---

The property of an algorithm that is aware of its goal and uses that knowledge to take educated steps towards the goal, or in the case of ${fref("programming-language-theory/concepts/backward-chaining-search.td")}, starting from the goal, and working backwards towards the ${fref("programming-language-theory/concepts/axiom.td")}s.
