---
_type: Concept
_label: 'Hygienic macro'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-3-syntactic-sugar.td")
tags:
  - 'compiler-implementation'
  - 'language-feature-design'
  - 'metaprogramming-self-reflection'
  - 'programming-paradigm'
---

Hygienic macros are analogous to ${fref("programming-language-theory/concepts/lexical-static-scope.td")} for ${fref("programming-language-theory/concepts/macro.td")}s: Macro variables are not just names, but rather binding information records.
