---
_type: Concept
_label: 'Inductive definition 2 dimensional inference rule format'
journey: fref("programming-language-theory/index.td")
status: 'learning'
---

🧰 Tools: Rocq (formerly Coq) (../../Tools/Tools/Rocq%20(formerly%20Coq)%202c2aa8fcd088809eb866e7aedf1b4061.md)

A **definition technique** that specifies a set or type by its base cases and rules for building new elements from existing ones.

A definition technique that specifies a set as the strongest set that is closed under a set of rules to derive membership of its elements.
