---
_type: Concept
title: 'Interpretation function'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
tags:
  - 'semantics'
---

A function mapping syntactic terms to mathematical objects (denotations) in a ${fref("programming-language-theory/concepts/semantic-domain.td")}, assigning meaning compositionally based on the structure of terms.
