---
_type: Concept
title: 'Intro pattern'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
tags:
  - 'formal-system'
  - 'language-feature-design'
  - 'proof-reason-technique'
  - 'semantics'
  - 'syntax-grammar'
---

[Rocq] A [tactic modifier](/programming-language-theory/concepts/tactic-modifier) in Rocq:(/programming-language-theory/concepts/rocq) that destructures [hypothesis](/programming-language-theory/concepts/hypothesis)es as they're introduced (like `intros [x y]` to unpack a pair or `intros [H|H]` for a disjunction).
