---
_type: Concept
_label: 'Involutive'
title: 'Involutive'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
tags:
  - 'set-theory-relation'
---

A property of a function where applying it twice returns the original value (i.e., f(f(x)) = x).

A **property** of a function where applying it twice returns the original value (i.e., `f(f(x)) = x`).
