---
_type: Concept
_label: 'Iterated inductive definition'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
tags:
  - 'logic'
  - 'proof-reason-technique'
  - 'set-theory-relation'
---

An ${fref("programming-language-theory/concepts/inductive-definition.td")} technique that specifies a set of elements as the strongest sets closed under a set of ${fref("programming-language-theory/concepts/inference-rule.td")}s - each inference rule may only refer to already defined sets or the currently defined one.
