---
_type: Concept
title: 'Join'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
tags:
  - 'order-lattice-theory'
---

In the context of a ${fref("programming-language-theory/concepts/partial-order.td")}, the least upper bound of a set $S$, denoted $\bigvee S$.
