---
_type: Concept
_label: 'Judgment assertion judgment form judgment form instances'
journey: fref("programming-language-theory/index.td")
status: 'learning'
---

- A ${fref("programming-language-theory/concepts/judgment-form.td")} is a relation, interpreted as a ${fref("programming-language-theory/concepts/predicate.td")}.

    Typically written as $- \ J$ (for unary relation).

- Take the judgment form above, the notation $a\ J$, for some value $a$, is an instance of the judgment form.
- Take the judgment form instance above, $a$ is the judgment form instance’s subject.
- A judgment/assertion is a stance on whether an instance of the judgment holds or not.
