---
_type: Concept
_label: 'Lambda expression'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
tags:
  - 'language-feature-design'
  - 'syntax-grammar'
---

A syntactic construct denoting an anonymous function, consisting of a list of ${fref("programming-language-theory/concepts/formal-parameter.td")}s and a body - e.g., $\lambda x.\ t$ or $(\text{lambda}\ (x)\ t)$.
