---
_type: Concept
title: 'Logical system'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

A formal framework comprising a syntax (well-formed formulas), ${fref("programming-language-theory/concepts/axiom.td")}s, and ${fref("programming-language-theory/concepts/inference-rule.td")}s that together determine which statements are ${fref("programming-language-theory/concepts/derivable.td")}.
