---
_type: Concept
_label: 'Macro'
title: 'Macro'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-3-syntactic-sugar.td")
---

A syntactic pattern that is expanded into other code at compile time via ${fref("programming-language-theory/concepts/macro-expansion.td")}, enabling metaprogramming by allowing code to generate or transform other code before execution.
