---
_type: Concept
title: 'Method'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
tags:
  - 'language-feature-design'
  - 'programming-paradigm'
---

A function defined within a class that operates on instances of that class, typically bound to and having implicit access to the object's state through this or self.

A function defined within a class that operates on instances of that class, typically bound to and having implicit access to the object's state through `this` or `self`.
