---
_type: Concept
_label: 'Micro gradual typing'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'language-feature-design'
  - 'semantics'
  - 'type-theory'
---

A ${fref("programming-language-theory/concepts/gradual-typing.td")} approach where type annotations can be added to any subset of variables within the same code, freely mixing typed and untyped expressions.

A Gradual typing approach where type annotations can be added to **any subset of variables** within the same code, freely mixing typed and untyped expressions.
