---
_type: Concept
title: 'Mixfix'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
tags:
  - 'set-theory-relation'
  - 'syntax-grammar'
---

A notation to write down an instance of an ${fref("programming-language-theory/concepts/n-place-relation.td")}. For example, for a ternary relation $R$, one can write $\Gamma \vdash t : T$ to denote $(\Gamma, t, T) \in R$.
