---
_type: Concept
_label: 'Mixin'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
---

A function that transforms a class into another class, typically adding behaviors to it assuming the class conforms to an interface, similar to a ${fref("programming-language-theory/concepts/class-extension.td")}.
