---
_type: Concept
title: 'Mutable'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
tags:
  - 'language-feature-design'
  - 'runtime'
  - 'semantics'
---

The property of an entity (variable, data structure, reference) whose contents can be modified in place after creation.
