---
_type: Concept
title: 'Mutation'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
tags:
  - 'language-feature-design'
  - 'semantics'
---

The act of modifying a value in place at a memory location, rather than producing a new value - introducing ${fref("programming-language-theory/concepts/state.td")} changes that depend on evaluation order and complicating equational reasoning.
