---
_type: Concept
_label: 'N-place relation'
title: 'N-place relation'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
tags:
  - 'set-theory-relation'
---

Given $n$ sets $X_1, X_2, ..., X_n$, the subset of the Cartesian product $X_1 \times X_2 \times ... \times X_n$.
