---
_type: Concept
title: 'Nonsensical term'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
tags:
  - 'semantics'
  - 'syntax-grammar'
---

Example: In the ${fref("programming-language-theory/concepts/untyped-calculus-of-booleans-and-numbers.td")}, the followings are nonsensical:

- $\text{succ}\ \text{tru}$
- $\text{if}\ 1\ \text{then}\ ...$
