---
_type: Concept
_label: 'Operational semantics'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

A style of semantics that defines the meaning of programs by syntactically transforming terms according to reduction rules, specifying execution either step-by-step (${fref("programming-language-theory/concepts/small-step-structural-operational-semantics-sos.td")}) or as a direct relation to final values (${fref("programming-language-theory/concepts/big-step-natural-operational-semantics.td")}).
