---
_type: Concept
title: 'Parsing'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
tags:
  - 'compiler-implementation'
  - 'linguistics'
  - 'syntax-grammar'
---

::: info
(Compiler implementation) The process of converting Concrete/Surface syntax into [Abstract syntax tree (AST)](/plt/concepts/abstract-syntax-tree-ast)s.
:::

::: info
(Syntax & Grammar, Linguistics) The process of converting a text into the terms of a Context-free grammar.
:::
