---
_type: Concept
_label: 'Principle of ordinary induction'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-2-mathematical-preliminaries.td")
---

A proof technique with a base case and an inductive step that assumes the property holds for the immediate predecessor to prove it for the successor.
