---
_type: Concept
_label: 'Procedure'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
tags:
  - 'language-feature-design'
---

A subroutine that performs actions primarily for ${fref("programming-language-theory/concepts/side-effect.td")}s rather than returning a value. Unlike functions, procedures emphasize imperative steps over computation of results.
