---
_type: Concept
_label: 'Programming paradigm'
title: 'Programming paradigm'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
tags:
  - 'programming-paradigm'
---

A style or philosophy of programming characterized by its core concepts and patterns (like functional, imperative, object-oriented, or logic programming).

A **style or philosophy** of programming characterized by its core concepts and patterns (like functional, imperative, object-oriented, or logic programming).
