---
_type: Concept
_label: 'Proof by simplification'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

Tools: Rocq (formerly Coq)

::: info
(Proof/Reason technique, Logic) A [proof technique](/programming-language-theory/concepts/proof-technique) that reduces expressions to simpler forms using definitional equalities, [computation rule](/programming-language-theory/concepts/computation-rule)s, or algebraic identities.
:::

::: info
(Formal system, Proof/Reason technique, Language feature/design, Programming paradigm) [Rocq] A Proof technique in Rocq (via `simpl` or `reflexivity`) that reduces expressions using Computation rules (unfolding, beta reduction, pattern matching).
:::
