---
_type: Concept
_label: 'Proof technique'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
tags:
  - 'language-feature-design'
  - 'logic'
  - 'programming-paradigm'
  - 'proof-reason-technique'
---

::: info
(Formal system, Proof/Reason technique, Language feature/design, Programming paradigm) [Rocq] In Rocq, a **conceptual strategy** for proving goals (like induction or case analysis), typically realized by corresponding tactics.
:::
