---
_type: Concept
_label: 'Rocq inductive definition'
title: 'Rocq inductive definition'
journey: fref("programming-language-theory/index.td")
status: 'learning'
---

It allows defining ${fref("programming-language-theory/concepts/algebraic-data-type.td")}s in Rocq, including ${fref("programming-language-theory/concepts/recursive-type.td")}s.

Its name bears resemblance to ${fref("programming-language-theory/concepts/inductive-definition.td")}.
