---
_type: Concept
title: 'Rocq'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

Tools: Rocq (formerly Coq)

- (Formal system, Language feature/design, Proof/Reason technique) An **interactive theorem prover** (formerly Coq) that enables formal verification of mathematical proofs and program correctness, using ${fref("programming-language-theory/concepts/dependent-type.td")}s and the ${fref("programming-language-theory/concepts/calculus-of-inductive-construction.td")}.

- Name history

    Formerly Coq (after Thierry Coquand + CoC abbreviation + the French rooster symbolizing pride), renamed Rocq in 2024 (honoring Rocquencourt, Inria's founding site, and evoking the roc, a mythical bird of strength).
