---
_type: Concept
_label: 'Rule'
title: 'Rule'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
  - fref("programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
tags:
  - 'logic'
---

Short-hand for ${fref("programming-language-theory/concepts/inference-rule.td")}.
