---
_type: Concept
_label: 'Rule schema inference rule concrete rule instance of an'
journey: fref("programming-language-theory/index.td")
status: 'learning'
---

An parameterized inference rules with ${fref("programming-language-theory/concepts/metavariable.td")}s that can be instantiated to ${fref("programming-language-theory/concepts/concrete-rule.td")}s or ${fref("programming-language-theory/concepts/inference-rule.td")}s.
