---
_type: Concept
_label: 'Runtime type error'
title: 'Runtime type error'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-1-introduction.td")
---

According to Types and programming languages, the class of undefined or undesirable behaviors that a ${fref("programming-language-theory/concepts/type-system.td")} is designed to prevent - whether they are actually eliminated depends on the soundness of the type system.

According to Types and programming languages, the class of undefined or undesirable behaviors that a type system is designed to prevent - **whether they are actually eliminated depends on the soundness of the type system**.
