---
_type: Concept
_label: 'Runtime type dispatch'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'language-feature-design'
  - 'metaprogramming-self-reflection'
  - 'programming-paradigm'
  - 'runtime'
  - 'semantics'
  - 'type-theory'
---

A pattern typically associated with ${fref("programming-language-theory/concepts/union-type.td")}s in which the type of a value is checked so that specialized logic can be carried out. ${fref("programming-language-theory/concepts/flow-sensitive-typing.td")} is especially useful.
