---
_type: Concept
_label: 'Runtime error'
title: 'Runtime error'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-1-learning-smol-standard-model-of-languages.td")
tags:
  - 'lambda-calculus'
  - 'runtime'
  - 'semantics'
---

::: info
(Runtime) An error that happens at runtime.
:::
