---
_type: Concept
_label: 'Runtime type information (RTTI)'
title: 'Runtime type information (RTTI)'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'language-feature-design'
  - 'metaprogramming-self-reflection'
  - 'runtime'
  - 'type-theory'
---

A mechanism that allows the reflection of the type of a value at runtime.
