---
_type: Concept
title: 'Safety check'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'design-principle'
  - 'language-feature-design'
  - 'programming-paradigm'
  - 'runtime'
---

A mechanism, either carried out by the runtime to enforce ${fref("programming-language-theory/concepts/language-safety.td")} / avoid ${fref("programming-language-theory/concepts/runtime-type-error.td")} or by programmers to avoid ${fref("programming-language-theory/concepts/runtime-error.td")}.
