---
_type: Concept
title: 'Scope'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
tags:
  - 'lambda-calculus'
  - 'semantics'
  - 'syntax-grammar'
---

::: info
(Semantics) The region of the code that a ${fref("programming-language-theory/concepts/binding.td")} takes effect.
:::

::: info
(Syntax & Grammar, Semantics) An **[Abstract binding tree (ABT)](/plt/concepts/abstract-binding-tree-abt)** *within which* the **bound identifier can be used**, either as a **placeholder** (in the case of a **variable declaration**) or as **the index of some Indexed operator** (in the case of a Symbol **declaration**).
:::
