---
_type: Concept
_label: 'Semantic domain'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
tags:
  - 'semantics'
---

The mathematical structure (e.g., sets, functions, lattices) in which terms are given meaning by a ${fref("programming-language-theory/concepts/denotational-semantics.td")}.
