---
_type: Concept
title: 'Small-step/Structural operational semantics (SOS)'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

A style of semantics which defines evaluation via ${fref("programming-language-theory/concepts/evaluation-statement-judgement.td")} of the form $t \to t'$, specifying how a term reduces by one atomic step at a time until reaching a ${fref("programming-language-theory/concepts/normal-form.td")}.
