---
_type: Concept
_label: 'Strong normalization'
title: 'Strong normalization'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'language-feature-design'
  - 'semantics'
---

The property of a language written in which every program always terminates.
