---
_type: Concept
_label: 'Structural/Abstract syntax'
title: 'Structural/Abstract syntax'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-5-the-untyped-pure-lambda-calculus.td")
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
tags:
  - 'compiler-implementation'
  - 'syntax-grammar'
---

::: info
(Syntax & Grammar) According to Practical foundations for programming languages, the program's tree structure ([Abstract syntax tree (AST)](/plt/concepts/abstract-syntax-tree-ast)) showing how phrases are built from ${fref("programming-language-theory/concepts/operator.td")}s and subphrases.
:::
