---
_type: Concept
title: 'Stuck term'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
tags:
  - 'lambda-calculus'
  - 'semantics'
---

A ${fref("programming-language-theory/concepts/lambda-calculus.td")} term that is in ${fref("programming-language-theory/concepts/normal-form.td")} but not a value.
