---
_type: Concept
_label: 'Subclass'
title: 'Subclass'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'language-feature-design'
  - 'programming-paradigm'
  - 'semantics'
---

::: info
(Semantics, Language feature/design, Programming paradigm) A ${fref("programming-language-theory/concepts/class.td")} that extends a parent class.
:::
