---
_type: Concept
_label: 'Subtyping'
title: 'Subtyping'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'language-feature-design'
  - 'programming-paradigm'
  - 'semantics'
  - 'type-theory'
---

The ${fref("programming-language-theory/concepts/type-system.td")} mechanism that defines and enforces when substitution is allowed between types.

The ${fref("programming-language-theory/concepts/type-system.td")} mechanism that defines and enforces **when substitution is allowed** between types.
