---
_type: Concept
title: 'Subtyping relation'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
---

Written $X <: Y$, a formal ordering on types meaning "$X$ is a ${fref("programming-language-theory/concepts/subtype.td")} of $Y$" - $X$ substitutes for $Y$.

Written $X <: Y$, a formal ordering on types meaning "$X$ is a ${fref("programming-language-theory/concepts/subtype.td")} of $Y$" - $X$ **substitutes for** $Y$.
