---
_type: Concept
title: 'Sum of products (SoP)'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'language-feature-design'
  - 'type-theory'
---

The structure of ${fref("programming-language-theory/concepts/algebraic-data-type.td")}s - sum because variants combine via "or" (one of mt or node), product because each variant's fields combine via "and" (a node has v and l and r).

The structure of ${fref("programming-language-theory/concepts/algebraic-data-type.td")}s - **sum** because variants combine via "or" (one of `mt` or `node`), **product** because each variant's fields combine via "and" (a `node` has `v` and `l` and `r`).
