---
_type: Concept
_label: 'Supertype'
title: 'Supertype'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'semantics'
  - 'set-theory-relation'
  - 'type-theory'
---

If $X$ is a ${fref("programming-language-theory/concepts/subtype.td")} of $Y$ then $Y$ is a supertype of $X$.
