---
_type: Concept
_label: 'Surface language'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-3-syntactic-sugar.td")
tags:
  - 'compiler-implementation'
  - 'language-feature-design'
  - 'syntax-grammar'
---

The user-facing syntax of a programming language, including ${fref("programming-language-theory/concepts/syntactic-sugar.td")} and conveniences, as opposed to the ${fref("programming-language-theory/concepts/core-calculus-language.td")} that programs are desugared into.
