---
_type: Concept
_label: 'Syntactic category'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
tags:
  - 'lambda-calculus'
  - 'syntax-grammar'
---

::: info
(Syntax & Grammar) According to Practical foundations for programming languages, largely analogous with ${fref("programming-language-theory/concepts/sort.td")}. Roughly means "syntactic type".
:::
