---
_type: Concept
_label: 'Tactic'
title: 'Tactic'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-1-basics-functional-programming-in-rocq.td")
---

Tools: Rocq (formerly Coq)

::: info
(Language feature/design, Formal system, Proof/Reason technique) A **proof Command** in ${fref("programming-language-theory/concepts/rocq.td")} that transforms the current ${fref("programming-language-theory/concepts/goal.td")} state, automating proof steps (like `intros`, `apply`, `rewrite`) to incrementally construct a proof term.
:::
