---
_type: Concept
title: 'Tagged union'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
tags:
  - 'language-feature-design'
  - 'programming-paradigm'
  - 'type-theory'
---

Synonym for ${fref("programming-language-theory/concepts/sum-type.td")} - "union" because it combines variants, "tagged" because each variant has an explicit ${fref("programming-language-theory/concepts/constructor-tag.td")} distinguishing it (unlike untagged ${fref("programming-language-theory/concepts/union-type.td")} types).

Synonym for Sum type - "union" because it combines variants, "tagged" because each variant has an explicit Constructor tag distinguishing it (unlike **untagged** Union type types).
