---
_type: Concept
_label: 'Term'
title: 'Term'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

A term is a syntactic phrase in a grammar that represents computation and evaluates to a value - unlike ${fref("programming-language-theory/concepts/expression.td")} which broadly encompasses any well-formed syntactic construct including types, patterns, and declarations.
