---
_type: Concept
title: 'The diamond problem'
journey: fref("programming-language-theory/index.td")
status: 'mastered'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-4-objects.td")
tags:
  - 'design-principle'
---

An ambiguity that arises in ${fref("programming-language-theory/concepts/multiple-inheritance.td")} when a class inherits from two classes that both inherit from a common ancestor, causing uncertainty about which inherited member to use.
