---
_type: Concept
_label: 'The plait programming language'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-2-evaluation.td")
tags:
  - 'language-feature-design'
---

A dialect of Lisp, based on Racket, but with ${fref("programming-language-theory/concepts/type-system.td")} resembling that of ML.
