---
_type: Concept
_label: 'Top-down construction'
title: 'Top-down construction'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/software-foundations/chapter-2-inductive-definitions.td")
tags:
  - 'logic'
  - 'proof-reason-technique'
  - 'set-theory-relation'
---

Synonymous with ${fref("programming-language-theory/concepts/backward-chaining.td")}.
