---
_type: Concept
title: 'Type error'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/programming-languages-application-and-interpretation/chapter-5-types.td")
tags:
  - 'type-theory'
---

According to Programming languages: Application and Interpretation, an inability to construct a proof that a given term has some consistent type.
