---
_type: Concept
_label: 'Value'
title: 'Value'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/types-and-programming-languages/chapter-3-untyped-arithmetic-expressions.td")
---

A ${fref("programming-language-theory/concepts/term.td")} in ${fref("programming-language-theory/concepts/normal-form.td")} that is not deemed a bad state.
