---
_type: Concept
_label: 'Variadic tree'
journey: fref("programming-language-theory/index.td")
status: 'reviewing'
books:
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
tags:
  - 'data-structure-algorithm'
---

A tree structure where operators can take a variable (not fixed) number of arguments, with that number determined by a ${fref("programming-language-theory/concepts/symbol.td")} index.
