---
_type: Concept
_label: 'Variable'
title: 'Variable'
journey: fref("programming-language-theory/index.td")
status: 'learning'
books:
  - fref("programming-language-theory/books/practical-foundations-for-programming-languages/chapter-1-abstract-syntax.td")
---

::: info
(Syntax & Grammar) According to Practical foundations for programming languages , specifically Chapter 1. Abstract syntax, a syntactic variable which is a placeholder for an [Abstract syntax tree (AST)](/plt/concepts/abstract-syntax-tree-ast) of a specific Sort.
:::
