---
_type: Flashcard
deck: 'design-aspect'
concepts:
  - fref("journeys/design/concepts/user-interface-ui.td")
  - fref("journeys/design/concepts/user-experience-ux.td")
---

::: flashcard
What is UI/UX?
=== key
- UI: The visual bridge between the user and the system.
- UX: The holistic quality of the user's interaction with the system, concerning its satisfaction, efficiency, intuitiveness as a whole.
:::
