---
_type: DesignFlashcard
_label: 'Give an example of a dilemma where affordance and anti-affordance cannot be both discoverable?'
deck: 'general'
concepts:
  - fref("design/concepts/affordance.td")
  - fref("design/concepts/discoverable.td")
  - fref("design/concepts/anti-affordance.td")
---

::: flashcard
Give an example of a dilemma where affordance and anti-affordance cannot be both discoverable?
=== key
:::
