---
_type: Flashcard
_label: 'How does HCD fit with industrial, experience and interaction design?'
deck: 'general'
concepts:
  - fref("design/concepts/industrial-design.td")
  - fref("design/concepts/experience.td")
  - fref("design/concepts/interaction-design.td")
  - fref("design/concepts/experience-design.td")
---

::: flashcard
How does HCD fit with industrial, experience and interaction design?
=== key
:::
