---
_type: schema
_extends: Journey
properties:
  tags:
    type: list['closures' | 'compiler implementation' | 'compilers' | 'computation theory' | 'concurrency theory' | 'continuation-passing style' | 'Coq' | 'data structure algorithm' | 'design principle' | 'domain theory' | 'formal system' | 'formal verification' | 'interpreters' | 'lambda calculus' | 'language design' | 'language feature design' | 'linguistics' | 'logic' | 'metaprogramming self reflection' | 'operational semantics' | 'order lattice theory' | 'other mathematics' | 'program analysis' | 'programming languages' | 'programming paradigm' | 'proof reason technique' | 'proof theory' | 'Rocq' | 'runtime' | 'Scheme' | 'semantics' | 'set theory relation' | 'syntax grammar' | 'theorem proving' | 'type systems' | 'type theory']?
---
